# coding=utf-8

# importing the libraries
# the keys_for_faiz_bot and lyrics libraries are .py files
from requests_oauthlib import OAuth1Session
import os
import tweepy
import time
from random import *

# setting up the authentication framework

client = tweepy.Client(
    consumer_key=str(os.environ.get('CONSUMER_KEY')),
    consumer_secret=str(os.environ.get('CONSUMER_SECRET')),
    access_token=str(os.environ.get('ACCESS_TOKEN')),
    access_token_secret=str(os.environ.get('ACCESS_TOKEN_SECRET'))
)
# defining variables to be used afterwards

lyrics = ["'ġhālib' burā na maan jo vaa.iz burā kahe \\ aisā bhī koī hai ki sab achchhā kaheñ jise",
          "'ġhālib' chhuTī sharāb par ab bhī kabhī kabhī \\ piitā huuñ roz-e-abr o shab-e-māhtāb meñ",
          "'ġhālib' mire kalām meñ kyūñkar mazā na ho \\ piitā huuñ dhoke ḳhusrav-e-shīrīñ-suḳhan ke paañv",
          "'ġhālib'-e-ḳhasta ke baġhair kaun se kaam band haiñ \\ roiye zaar zaar kyā kījiye haa.e haa.e kyuuñ",
          'Dare kyuuñ merā qātil kyā rahegā us kī gardan par \\ vo ḳhuuñ jo chashm-e-tar se umr bhar yuuñ dam-ba-dam nikle',
          "aa hī jaatā vo raah par 'ġhālib' \\ koī din aur bhī jiye hote",
          'aa ki mirī jaan ko qarār nahīñ hai \\ tāqat-e-bedād-e-intizār nahīñ hai',
          'aa.e ho kal aur aaj hī kahte ho ki jā.ūñ \\ maanā ki hamesha nahīñ achchhā koī din aur',
          'aa.ī yak-umr se ma.azūr-e-tamāsha nargis \\ chashm-e-shabnam meñ na TuuTā mizha-e-ḳhār hunūz',
          'aabrū kyā ḳhaak us gul kī ki gulshan meñ nahīñ \\ hai garebāñ nañg-e-pairāhan jo dāman meñ nahīñ',
          'aage aatī thī hāl-e-dil pe hañsī \\ ab kisī baat par nahīñ aatī',
          'aah ko chāhiye ik umr asar hote tak \\ kaun jiitā hai tirī zulf ke sar hote tak',
          'aah kā kis ne asar dekhā hai \\ ham bhī ek apnī havā bāñdhte haiñ',
          'aaj ham apnī pareshāni-e-ḳhātir un se \\ kahne jaate to haiñ par dekhiye kyā kahte haiñ',
          'aaj vaañ teġh o kafan bāñdhe hue jaatā huuñ maiñ \\ uzr mere qatl karne meñ vo ab lāveñge kyā',
          'aalam ġhubār-e-vahshat-e-majnūñ hai sar-ba-sar \\ kab tak ḳhayāl-e-turra-e-lailā kare koī',
          'aatā hai mere qatl ko par josh-e-rashk se \\ martā huuñ us ke haath meñ talvār dekh kar',
          'ab jafā se bhī haiñ mahrūm ham allāh allāh \\ is qadar dushman-e-arbāb-e-vafā ho jaanā',
          'abrū se hai kyā us nigah-e-nāz ko paivand \\ hai tiir muqarrar magar is kī hai kamāñ aur',
          'achchhā hai sar-añgusht-e-hinā.ī kā tasavvur \\ dil meñ nazar aatī to hai ik buuñd lahū kī',
          'adab hai aur yahī kashmakash to kyā kiije \\ hayā hai aur yahī gū-magū to kyūñkar ho',
          'adam hai ḳhair-ḳhvāh-e-jalva ko zindān-e-betābi \\ ḳhirām-e-nāz barq-e-ḳhirman-e-sa.ī-e-sipand aayā',
          'afsurdagī nahīñ tarab-inshā-e-iltifāt \\ haañ dard ban ke dil meñ magar jā kare koī',
          'agar vo sarv-qad garm-e-ḳhirām-e-nāz aa jaave \\ kaf-e-har-ḳhāk-e-gulshan shakl-e-qamrī nāla-farsā ho',
          'agle vaqtoñ ke haiñ ye log inheñ kuchh na kaho \\ jo mai o naġhma ko andoh-rubā kahte haiñ',
          'ahbāb chārasāzi-e-vahshat na kar sake \\ zindāñ meñ bhī ḳhayāl bayābāñ-navard thā',
          'ai tirā ġhamza yak-qalam-añgez \\ ai tirā zulm sar-ba-sar andāz',
          'ai vā.e-ġhaflat-e-nigah-e-shauq varna yaañ \\ har paara sañg laḳht-e-dil-e-koh-e-tūr thā',
          'aisā āsāñ nahīñ lahū ronā \\ dil meñ tāqat jigar meñ haal kahāñ',
          'alarraġhm-e-dushamn shahīd-e-vafā huuñ \\ mubārak mubārak salāmat salāmat',
          'allāh-re zauq-e-dasht-navardī ki ba.ad-e-marg \\ hilte haiñ ḳhud-ba-ḳhud mire andar kafan ke paañv',
          'alāva iid ke miltī hai aur din bhī sharāb \\ gadā-e-kūcha-e-mai-ḳhāna nā-murād nahīñ',
          'apnī rusvā.ī meñ kyā chaltī hai sa.ī \\ yaar hī hañgāma-ārā chāhiye',
          'arz kiije jauhar-e-andesha kī garmī kahāñ \\ kuchh ḳhayāl aayā thā vahshat kā ki sahrā jal gayā',
          'arz-e-niyāz-e-ishq ke qābil nahīñ rahā \\ jis dil pe naaz thā mujhe vo dil nahīñ rahā',
          'arz-e-nāz-e-shoḳhi-e-dandāñ barā.e-ḳhanda hai \\ dāvā-e-jamiyat-e-ahbāb jā-e-ḳhanda hai',
          'asar-e-ābla se jāda-e-sahrā-e-junūñ \\ sūrat-e-rishta-e-gauhar hai charāġhāñ mujh se',
          'asl-e-shuhūd-o-shāhid-o-mash.hūd ek hai \\ hairāñ huuñ phir mushāhida hai kis hisāb meñ',
          'aur bāzār se le aa.e agar TuuT gayā \\ sāġhar-e-jam se mirā jām-e-sifāl achchhā hai',
          'az-bas-ki sikhātā hai ġham zabt ke andāze \\ jo daaġh nazar aayā ik chasm-numā.ī hai',
          'ba-pech-o-tāb-e-havas silk-e-āfiyat mat toḌ \\ nigāh-e-ajz sar-e-rishta-e-salāmat hai',
          'ba-qadr-e-hasrat-e-dil chāhiye zauq-e-ma.āsī bhī \\ bharūñ yak-gosha-e-dāman gar āb-e-haft-dariyā ho',
          'ba-rañg-e-kāġhaz-e-ātish-zada nairañg-e-betābī \\ hazār ā.īna dil bāñdhe hai bāl-e-yak-tapīdan par',
          'ba-rañg-e-shīsha huuñ yak-gosha-e-dil-e-ḳhālī \\ kabhī parī mirī ḳhalvat meñ aa nikaltī hai',
          'ba-sail-e-ashk laḳht-e-dil hai dāman-gīr mizhgāñ kā \\ ġharīq-e-bahr jūyā-e-ḳhas-o-ḳhāshāk-e-sāhil hai',
          'ba-saḳhtī-hā-e-qaid-e-zindagī mālūm āzādī \\ sharar bhī said-e-dām-e-rishta-e-rag-hā-e-ḳhārā hai',
          'baat par vaañ zabān kaTtī hai \\ vo kaheñ aur sunā kare koī',
          'baaġh pā kar ḳhafaqānī ye Darātā hai mujhe \\ sāya-e-shāḳh-e-gul af.ī nazar aatā hai mujhe',
          'baaġh tujh bin gul-e-nargis se Darātā hai mujhe \\ chāhūñ gar sair-e-chaman aañkh dikhātā hai mujhe',
          'bad-gumāñ hotā hai vo kāfir na hotā kaash ke \\ is qadar zauq-e-navā-e-murġh-e-bustānī mujhe',
          'baham bālīdan-e-sañg-o-gul-e-sahrā ye chāhe hai \\ ki tār-e-jāda bhī kohsār ko zunnār-e-mīnā ho',
          'bahut dinoñ meñ taġhāful ne tere paidā kī \\ vo ik nigah ki ba-zāhir nigāh se kam hai',
          'bahut sahī ġham-e-gītī sharāb kam kyā hai \\ ġhulām-e-sāqī-e-kausar huuñ mujh ko ġham kyā hai',
          'baiza-āsā nañg-e-bāl-o-par hai ye kunj-e-qafas \\ az-sar-e-nau zindagī ho gar rihā ho jā.iye',
          'bajā hai gar na sune nāla-hā-e-bulbul-e-zār \\ ki gosh-e-gul nam-e-shabnam se pamba-āgīñ hai',
          'bak rahā huuñ junūñ meñ kyā kyā kuchh \\ kuchh na samjhe ḳhudā kare koī',
          'balā se gar mizha-e-yār tishna-e-ḳhūñ hai \\ rakhūñ kuchh apnī bhī mizhgān-e-ḳhūñ fishāñ ke liye',
          'balā se haiñ jo ye pesh-e-nazar dar-o-dīvār \\ nigāh-e-shauq ko haiñ bāl-o-par dar-o-dīvār',
          'ban gayā teġh-e-nigāh-e-yār kā sañg-e-fasāñ \\ marhabā maiñ kyā mubārak hai girāñ-jānī mujhe',
          'bandagī meñ bhī vo āzāda o ḳhud-bīñ haiñ ki ham \\ ulTe phir aa.e dar-e-ka.aba agar vā na huā',
          'bar-rū-e-shash-jahat dar-e-ā.īna baaz hai \\ yaañ imtiyāz-e-nāqis-o-kāmil nahīñ rahā',
          'barshikāl-e-girya-e-āshiq hai dekhā chāhiye \\ khil ga.ī mānind-e-gul sau jā se dīvār-e-chaman',
          'bas hujūm-e-nā-umīdī ḳhaak meñ mil jā.egī \\ ye jo ik lazzat hamārī sa.ī-e-be-hāsil meñ hai',
          'bas ki paa.ī yaar kī rañgīñ-adā.ī se shikast \\ hai kulāh-e-nāz-e-gul bar tāq-e-dīvār-e-chaman',
          'bas-ki dauḌe hai rag-e-tāk meñ ḳhuuñ ho ho kar \\ shahpar-e-rañg se hai bāl-kushā mauj-e-sharāb',
          'bas-ki dushvār hai har kaam kā āsāñ honā \\ aadmī ko bhī mayassar nahīñ insāñ honā',
          'bas-ki haiñ ham ik bahār-e-nāz ke maare hue \\ jalva-e-gul ke sivā gard apne madfan meñ nahīñ',
          'bas-ki thī fasl-e-ḳhizān-e-chamanistān-e-suḳhan \\ rañg-e-shohrat na diyā tāza-ḳhayālī ne mujhe',
          'bazm-e-qadah se aish-e-tamannā na rakh ki rañg \\ said-e-ze-dām-e-jasta hai us dām-gāh kā',
          'be-dar-o-dīvār sā ik ghar banāyā chāhiye \\ koī ham-sāya na ho aur pāsbāñ koī na ho',
          "be-e'tidāliyoñ se subuk sab meñ ham hue \\ jitne ziyāda ho ga.e utne hī kam hue",
          'be-mai kise hai tāqat-e-āshob-e-āgahī \\ khīñchā hai ijz-e-hausla ne ḳhat ayāġh kā',
          'be-niyāzī had se guzrī banda-parvar kab talak \\ ham kaheñge hāl-e-dil aur aap farmāveñge kyā',
          'be-talab deñ to mazā us meñ sivā miltā hai \\ vo gadā jis ko na ho ḳhū-e-savāl achchhā hai',
          'be-ḳhudī bistar-e-tamhīd-e-farāġhat ho jo \\ pur hai saa.e kī tarah merā shabistāñ mujh se',
          'be-ḳhūn-e-dil hai chashm meñ mauj-e-nigah ġhubār \\ ye mai-kada ḳharāb hai mai ke surāġh kā',
          'bharam khul jaa.e zālim tere qāmat kī darāzī kā \\ agar is turra-e-pur-pech-o-ḳham kā pech-o-ḳham nikle',
          'bhāge the ham bahut so usī kī sazā hai ye \\ ho kar asiir dābte haiñ rāhzan ke paañv',
          'bisāt-e-ijz meñ thā ek dil yak qatra ḳhuuñ vo bhī \\ so rahtā hai ba-andāz-e-chakīdan sar-nigūñ vo bhī',
          'bosa dete nahīñ aur dil pe hai har lahza nigāh \\ jī meñ kahte haiñ ki muft aa.e to maal achchhā hai',
          'bosa nahīñ na dījiye dushnām hī sahī \\ āḳhir zabāñ to rakhte ho tum gar dahāñ nahīñ',
          'bulbul ke kārobār pe haiñ ḳhanda-hā-e-gul \\ kahte haiñ jis ko ishq ḳhalal hai dimāġh kā',
          'bāzīcha-e-atfāl hai duniyā mire aage \\ hotā hai shab-o-roz tamāshā mire aage',
          'bāġh-e-shagufta terā bisāt-e-nashāt-e-dil \\ abr-e-bahār ḳhum-kada kis ke dimāġh kaa',
          'bū-e-gul nāla-e-dil dūd-e-charāġh-e-mahfil \\ jo tirī bazm se niklā so pareshāñ niklā',
          'chaak kī ḳhvāhish agar vahshat ba-uryānī kare \\ sub.h ke mānind zaḳhm-e-dil garebānī kare',
          'chaak mat kar jaib be-ayyām-e-gul \\ kuchh udhar kā bhī ishārā chāhiye',
          'chaal jaise kaḌī kamān kā tiir \\ dil meñ aise ke jā kare koī',
          'chaar mauj uThtī hai tūfān-e-tarab se har sū \\ mauj-e-gul mauj-e-shafaq mauj-e-sabā mauj-e-sharāb',
          'chaar sū-e-dahr meñ bāzār-e-ġhaflat garm hai \\ aql ke nuqsāñ se uThtā hai ḳhayāl-e-intifā.a',
          'chashm dallāl-e-jins-e-rusvā.ī \\ dil ḳharīdār-e-zauq-e-ḳhvārī hai',
          'chashm-e-ḳhūbāñ mai-farosh-e-nashshah-zār-e-nāz hai \\ surma goyā mauj-e-dūd-e-shola-e-āvāz hai',
          'chashm-e-ḳhūbāñ ḳhāmushī meñ bhī navā-pardāz hai \\ surma to kahve ki dūd-e-sho.ala-e-āvāz hai',
          'chhoḌā mah-e-naḳhshab kī tarah dast-e-qazā ne \\ ḳhurshīd hunūz us ke barābar na huā thā',
          'chhoḌā na rashk ne ki tire ghar kā naam luuñ \\ har ik se pūchhtā huuñ ki jā.ūñ kidhar ko maiñ',
          'chhoḌūñgā maiñ na us but-e-kāfir kā pūjnā \\ chhoḌe na ḳhalq go mujhe kāfar kahe baġhair',
          'chipak rahā hai badan par lahū se pairāhan \\ hamāre jaib ko ab hājat-e-rafū kyā hai',
          'chāhiye achchhoñ ko jitnā chāhiye \\ ye agar chāheñ to phir kyā chāhiye',
          'chāhne ko tere kyā samjhā thā dil \\ baare ab is se bhī samjhā chāhiye',
          "chāhte haiñ ḳhūb-rūyoñ ko 'asad' \\ aap kī sūrat to dekhā chāhiye",
          'chāk-e-jigar se jab rah-e-pursish na vā huī \\ kyā fā.eda ki jaib ko rusvā kare koī',
          'daa.im paḌā huā tire dar par nahīñ huuñ maiñ \\ ḳhaak aisī zindagī pe ki patthar nahīñ huuñ maiñ',
          'dahr meñ naqsh-e-vafā vaj.h-e-tasallī na huā \\ hai ye vo lafz ki sharminda-e-ma.anī na huā',
          'dair nahīñ haram nahīñ dar nahīñ āstāñ nahīñ \\ baiThe haiñ rahguzar pe ham ġhair hameñ uThā.e kyuuñ',
          'dam liyā thā na qayāmat ne hanūz \\ phir tirā vaqt-e-safar yaad aayā',
          'dar-parda unheñ ġhair se hai rabt-e-nihānī \\ zāhir kā ye parda hai ki parda nahīñ karte',
          'dar-ḳhur-e-arz nahīñ jauhar-e-bedād ko jā \\ nigah-e-nāz hai surme se ḳhafā mere ba.ad',
          'dar-ḳhur-e-qahr-o-ġhazab jab koī ham sā na huā \\ phir ġhalat kyā hai ki ham sā koī paidā na huā',
          'dard minnat-kash-e-davā na huā \\ maiñ na achchhā huā burā na huā',
          'dard-e-dil likhūñ kab tak jā.ūñ un ko dikhlā duuñ \\ uñgliyāñ figār apnī ḳhāma ḳhūñ-chakāñ apnā',
          'darkār hai shaguftan-e-gul-hā-e-aish ko \\ sub.h-e-bahār pumba-e-mīnā kaheñ jise',
          'dars-e-tapish hai barq ko ab jis ke naam se \\ vo dil hai ye ki jis kā taḳhallus subūr thā',
          'dars-e-unvān-e-tamāshā ba-taġhāful ḳhush-tar \\ hai nigah rishta-e-shīrāza-e-mizhgāñ mujh se',
          'dashna-e-ġhamza jāñ-sitāñ nāvak-e-nāz be-panāh \\ terā hī aks-e-ruḳh sahī sāmne tere aa.e kyuuñ',
          'dashne ne kabhī muñh na lagāyā ho jigar ko \\ ḳhanjar ne kabhī baat na pūchhī ho gulū kī',
          'dast-gāh-e-dīda-e-ḳhūñ-bār-e-majnūñ dekhnā \\ yak-bayābāñ jalva-e-gul farsh-e-pā-andāz hai',
          'de daad ai falak dil-e-hasrat-parast kī \\ haañ kuchh na kuchh talāfī-e-māfāt chāhiye',
          'de vo jis qadar zillat ham hañsī meñ Tāleñge \\ baare āshnā niklā un kā pāsbāñ apnā',
          'dekh kar dar-parda garm-e-dāman-afshānī mujhe \\ kar ga.ī vābasta-e-tan merī uryānī mujhe',
          'dekhnā taqrīr kī lazzat ki jo us ne kahā \\ maiñ ne ye jaanā ki goyā ye bhī mere dil meñ hai',
          'dekho to dil-farebi-e-andāz-e-naqsh-e-pā \\ mauj-e-ḳhirām-e-yār bhī kyā gul katar ga.ī',
          'dete haiñ jannat hayāt-e-dahr ke badle \\ nashsha ba-andāza-e-ḳhumār nahīñ hai',
          'dhamkī meñ mar gayā jo na bāb-e-nabard thā \\ ishq-e-nabard-pesha talabgār-e-mard thā',
          'dhotā huuñ jab maiñ piine ko us sīm-tan ke paañv \\ rakhtā hai zid se khīñch ke bāhar lagan ke paañv',
          'dil guzargāh-e-ḳhayāl-e-mai-o-sāġhar hī sahī \\ gar nafas jāda-e-sar-manzil-e-taqvī na huā',
          'dil huā kasmakash-e-chāra-e-zehmat meñ tamām \\ miT gayā ghisne meñ is uqde kā vā ho jaanā',
          'dil hī to hai na sang-o-ḳhisht dard se bhar na aa.e kyuuñ \\ ro.eñge ham hazār baar koī hameñ satā.e kyuuñ',
          'dil ko ham sarf-e-vafā samjhe the kyā ma.alūm thā \\ ya.anī ye pahle hī nazr-e-imtihāñ ho jā.egā',
          'dil ko āñkhoñ ne phañsāyā kyā magar \\ ye bhī halqe haiñ tumhāre daam ke',
          "dil lagā kar aap bhī 'ġhālib' mujhī se ho ga.e \\ ishq se aate the maane mīrzā sāhab mujhe",
          'dil meñ aa jaa.e hai hotī hai jo fursat ġhash se \\ aur phir kaun se naale ko rasā kahte haiñ',
          "dil meñ phir girye ne ik shor uThāyā 'ġhālib' \\ aah jo qatra na niklā thā so tūfāñ niklā",
          'dil meñ zauq-e-vasl o yād-e-yār tak baaqī nahīñ \\ aag is ghar meñ lagī aisī ki jo thā jal gayā',
          'dil mirā soz-e-nihāñ se be-muhābā jal gayā \\ ātish-e-ḳhāmosh kī mānind goyā jal gayā',
          'dil o diiñ naqd lā saaqī se gar saudā kiyā chāhe \\ ki us bāzār meñ sāġhar matā-e-dast-gardāñ hai',
          'dil se tirī nigāh jigar tak utar ga.ī \\ donoñ ko ik adā meñ razā-mand kar ga.ī',
          'dil se uThā lutf-e-jalva-hā-e-ma.ānī \\ ġhair-e-gul ā.īna-e-bahār nahīñ hai',
          'dil to dil vo dimāġh bhī na rahā \\ shor-e-saudā-e-ḳhatt-o-ḳhāl kahāñ',
          'dil tā jigar ki sāhil-e-dariyā-e-ḳhūñ hai ab \\ is rahguzar meñ jalva-e-gul aage gard thā',
          'dil ḳhūñ-shuda-e-kashmakash-e-hasrat-e-dīdār \\ ā.īna ba-dast-e-but-e-bad-mast hinā hai',
          'dil-e-hasrat-zada thā mā.ida-e-lazzat-e-dard \\ kaam yāroñ kā ba-qadr-e-lab-o-dandāñ niklā',
          'dil-e-nādāñ tujhe huā kyā hai \\ āḳhir is dard kī davā kyā hai',
          'dil-lagī kī aarzū bechain rakhtī hai hameñ \\ varna yaañ be-raunaqī sūd-e-charāġh-e-kushta hai',
          'dimāġh-e-itr-e-pairāhan nahīñ hai \\ ġham-e-āvārgī-hā-e-sabā kyā',
          'diyā hai dil agar us ko bashar hai kyā kahiye \\ huā raqīb to ho nāma-bar hai kyā kahiye',
          'do-ālam kī hastī pe ḳhatt-e-fanā khīñch \\ dil-o-dast-e-arbāb-e-himmat salāmat',
          'donoñ jahān de ke vo samjhe ye ḳhush rahā \\ yaañ aa paḌī ye sharm ki takrār kyā kareñ',
          'dost ġham-ḳhvārī meñ merī sa.ī farmāveñge kyā \\ zaḳhm ke bharte talak nāḳhun na baḌh jāveñge kyā',
          "dost-dār-e-dushman hai e'timād-e-dil ma.alūm \\ aah be-asar dekhī naala nā-rasā paayā",
          'dostī kā parda hai begānagī \\ muñh chhupānā ham se chhoḌā chāhiye',
          'dushmanī ne merī khoyā ġhair ko \\ kis qadar dushman hai dekhā chāhiye',
          'dām-e-har-mauj meñ hai halqa-e-sad-kām-e-nahañg \\ dekheñ kyā guzre hai qatre pe guhar hote tak',
          'dāġh-e-atfāl hai dīvāna ba-kohsār hunūz \\ ḳhalvat-e-sañg meñ hai naala talab-gār hunūz',
          'dāġh-e-rabt-e-ham haiñ ahl-e-bāġh gar gul ho shahīd \\ laala chashm-e-hasrat-ālūd-e-charāġh-e-kushta hai',
          'dī sādgī se jaan paḌūñ kohkan ke paañv \\ haihāt kyuuñ na TuuT ga.e pīr-zan ke paañv',
          'fahm zanjīrī-e-be-rabtī-e-dil hai yā-rab \\ kis zabāñ meñ hai laqab ḳhvāb-e-pareshāñ merā',
          'falak na duur rakh us se mujhe ki maiñ hī nahīñ \\ darāz-dasti-e-qātil ke imtihāñ ke liye',
          'falak se ham ko aish-e-rafta kā kyā kyā taqāzā hai \\ matā-e-burda ko samjhe hue haiñ qarz rahzan par',
          'fanā ko sauñp gar mushtāq hai apnī haqīqat kā \\ faroġh-e-tāla-e-ḳhāshāk hai mauqūf gulḳhan par',
          'fanā tālīm-e-dars-e-be-ḳhudī huuñ us zamāne se \\ ki majnūñ laam alif likhtā thā dīvār-e-dabistāñ par',
          'faroġh-e-husn se hotī hai hall-e-mushkil-e-āshiq \\ na nikle sham.a ke pā se nikāle gar na ḳhaar ātish',
          'faroġh-e-shola-e-ḳhas yak-nafas hai \\ havas ko pās-e-nāmūs-e-vafā kyā',
          'farāġhat kis qadar rahtī mujhe tashvīsh-e-marham se \\ baham gar sulh karte pāra-hā-e-dil namak-dāñ par',
          'fashār-e-tañgī-e-ḳhalvat se bantī hai shabnam \\ sabā jo ġhunche ke parde meñ jā nikaltī hai',
          'fazā-e-ḳhanda-e-gul tang o zauq-e-aish be-parvā \\ farāġhat-gāh-e-āġhosh-e-vidā-e-dil-pasand aayā',
          'fikr-e-duniyā meñ sar khapātā huuñ \\ maiñ kahāñ aur ye vabāl kahāñ',
          'fursat-e-kārobār-e-shauq kise \\ zauq-e-nazzāra-e-jamāl kahāñ',
          'fusūn-e-yak-dilī hai lazzat-e-bedād dushman par \\ ki vajd-e-barq juuñ parvāna bāl-afshāñ hai ḳhirman par',
          'fāriġh mujhe na jaan ki mānind-e-sub.h-o-mehr \\ hai dāġh-e-ishq zīnat-e-jeb-e-kafan hunūz',
          'ga.ī vo baat ki ho guftugū to kyūñkar ho \\ kahe se kuchh na huā phir kaho to kyūñkar ho',
          'gadā samajh ke vo chup thā mirī jo shāmat aa.ī \\ uThā aur uTh ke qadam maiñ ne pāsbāñ ke liye',
          'gar kiyā nāseh ne ham ko qaid achchhā yuuñ sahī \\ ye junūn-e-ishq ke andāz chhuT jāveñge kyā',
          'gar ḳhāmushī se fā.eda iḳhfā-e-hāl hai \\ ḳhush huuñ ki merī baat samajhnī muhāl hai',
          'garche hai kis kis burā.ī se vale bā.īñ-hama \\ zikr merā mujh se behtar hai ki us mahfil meñ hai',
          'ghar jab banā liyā tire dar par kahe baġhair \\ jānegā ab bhī tū na mirā ghar kahe baġhair',
          'ghar meñ thā kyā ki tirā ġham use ġhārat kartā \\ vo jo rakhte the ham ik hasrat-e-tāmīr so hai',
          'girya chāhe hai ḳharābī mire kāshāne kī \\ dar o dīvār se Tapke hai bayābāñ honā',
          'girya nikāle hai terī bazm se mujh ko \\ haa.e ki rone pe iḳhtiyār nahīñ hai',
          'go samajhtā nahīñ par husn-e-talāfī dekho \\ shikva-e-jaur se sargarm-e-jafā hotā hai',
          'go zindagi-e-zāhid-e-be-chāra abas hai \\ itnā hai ki rahtī to hai tadbīr vazū kī',
          'gulshan ko tirī sohbat az-bas-ki ḳhush aa.ī hai \\ har ġhunche kā gul honā āġhosh-kushā.ī hai',
          "guzrā 'asad' masarrat-e-paiġhām-e-yār se \\ qāsid pe mujh ko rashk-e-savāl-o-javāb hai",
          'haañ ai falak-e-pīr javāñ thā abhī aarif \\ kyā terā bigaḌtā jo na martā koī din aur',
          'haañ bhalā kar tirā bhalā hogā \\ aur darvesh kī sadā kyā hai',
          'haañ vo nahīñ ḳhudā-parast jaao vo bevafā sahī \\ jis ko ho diin o dil aziiz us kī galī meñ jaa.e kyuuñ',
          'had chāhiye sazā meñ uqūbat ke vāste \\ āḳhir gunāhgār huuñ kāfar nahīñ huuñ maiñ',
          'hai adam meñ ġhuncha mahv-e-ibrat-e-anjām-e-gul \\ yak-jahāñ zaanū ta.ammul dar-qafā-e-ḳhanda hai',
          'hai bas-ki har ik un ke ishāre meñ nishāñ aur \\ karte haiñ mohabbat to guzartā hai gumāñ aur',
          'hai chashm-e-tar meñ hasrat-e-dīdār se nihāñ \\ shauq-e-ināñ guseḳhta dariyā kaheñ jise',
          "hai dil-e-shorīda-e-'ġhālib' tilism-e-pech-o-tāb \\ rahm kar apnī tamannā par ki kis mushkil meñ hai",
          'hai hai ḳhudā-na-ḳhvāsta vo aur dushmanī \\ ai shauq-e-munfa.il ye tujhe kyā ḳhayāl hai',
          'hai josh-e-gul bahār meñ yaañ tak ki har taraf \\ uḌte hue ulajhte haiñ murġh-e-chaman ke paañv',
          'hai kis qadar halāk-e-fareb-e-vafā-e-gul \\ bulbul ke kārobār pe haiñ ḳhanda-hā-e-gul',
          'hai kuchh aisī hī baat jo chup huuñ \\ varna kyā baat kar nahīñ aatī',
          'hai kushād-e-ḳhātir-e-vā-basta dar rahn-e-suḳhan \\ thā tilism-e-qufl-e-abjad ḳhāna-e-maktab mujhe',
          'hai kyā jo kas ke bāñdhiye merī balā Dare \\ kyā jāntā nahīñ huuñ tumhārī kamar ko maiñ',
          'hai mushtamil numūd-e-suvar par vajūd-e-bahar \\ yaañ kyā dharā hai qatra o mauj-o-habāb meñ',
          'hai nazākat bas ki fasl-e-gul meñ me.amār-e-chaman \\ qālib-e-gul meñ Dhalī hai ḳhisht-e-dīvār-e-chaman',
          'hai nāz-e-muflisāñ zar-e-az-dast-rafta par \\ huuñ gul-farosh-e-shoḳhi-e-dāġh-e-kohan hunūz',
          'hai par-e-sarhad-e-idrāk se apnā masjūd \\ qible ko ahl-e-nazar qibla-numā kahte haiñ',
          'hai rañg-e-lāla-o-gul-o-nasrīñ judā judā \\ har rañg meñ bahār kā isbāt chāhiye',
          'hai sabza-zār har dar-o-dīvār-e-ġham-kada \\ jis kī bahār ye ho phir us kī ḳhizāñ na pūchh',
          'hai sarīr-e-ḳhāma rezish-hā-e-istiqbāl-e-nāz \\ naama ḳhud paiġhām ko bāl-o-par-e-parvāz hai',
          'hai shikastan se bhī dil naumīd yā rab kab talak \\ ābgīna koh par arz-e-girāñ-jānī kare',
          'hai tevrī chaḌhī huī andar naqāb ke \\ hai ik shikan paḌī huī tarf-e-naqāb meñ',
          'hai vasl hijr ālam-e-tamkīn-o-zabt meñ \\ māshūq-e-shoḳh o āshiq-e-dīvāna chāhiye',
          'hai ye barsāt vo mausam ki ajab kyā hai agar \\ mauj-e-hastī ko kare faiz-e-havā mauj-e-sharāb',
          'hai ḳhabar garm un ke aane kī \\ aaj hī ghar meñ boriyā na huā',
          'hai ḳhūn-e-jigar josh meñ dil khol ke rotā \\ hote jo ka.ī dīda-e-ḳhūñ-nāba-fishāñ aur',
          'hairāñ huuñ dil ko ro.uuñ ki pīTūñ jigar ko maiñ \\ maqdūr ho to saath rakhūñ nauhagar ko maiñ',
          'haiñ aaj kyuuñ zalīl ki kal tak na thī pasand \\ gustāḳhi-e-farishta hamārī janāb meñ',
          "haiñ aur bhī duniyā meñ suḳhan-var bahut achchhe \\ kahte haiñ ki 'ġhālib' kā hai andāz-e-bayāñ aur",
          'halqe haiñ chashm-hā-e-kushāda ba-sū-e-dil \\ har tār-e-zulf ko nigah-e-surma-sā kahūñ',
          'ham aur vo be-sabab rañj-āshnā dushman ki rakhtā hai \\ shuā-e-mehr se tohmat nigah kī chashm-e-rauzan par',
          'ham bhī dushman to nahīñ haiñ apne \\ ġhair ko tujh se mohabbat hī sahī',
          'ham haiñ mushtāq aur vo be-zār \\ yā ilāhī ye mājrā kyā hai',
          'ham kahāñ qismat āzmāne jaa.eñ \\ tū hī jab ḳhanjar-āzmā na huā',
          'ham ko sitam aziiz sitamgar ko ham aziiz \\ nā-mehrbāñ nahīñ hai agar mehrbāñ nahīñ',
          'ham ko un se vafā kī hai ummīd \\ jo nahīñ jānte vafā kyā hai',
          'ham par jafā se tark-e-vafā kā gumāñ nahīñ \\ ik chheḌ hai vagarna murād imtihāñ nahīñ',
          'ham rashk ko apne bhī gavārā nahīñ karte \\ marte haiñ vale un kī tamannā nahīñ karte',
          'ham se abas hai gumān-e-ranjish-e-ḳhātir \\ ḳhaak meñ ushshāq kī ġhubār nahīñ hai',
          'ham se chhūTā qimār-ḳhāna-e-ishq \\ vaañ jo jāveñ girah meñ maal kahāñ',
          'ham se rañj-e-betābī kis tarah uThāyā jaa.e \\ daaġh pusht-e-dast-e-ijz sho.ala ḳhas-ba-dandāñ hai',
          'hamāre zehn meñ us fikr kā hai naam visāl \\ ki gar na ho to kahāñ jaa.eñ ho to kyūñkar ho',
          'hamārī sādgī thī iltifāt-e-nāz par marnā \\ tirā aanā na thā zālim magar tamhīd jaane kī',
          'har bul-havas ne husn-parastī shi.ār kī \\ ab ābrū-e-sheva-e-ahl-e-nazar ga.ī',
          'har chand subuk-dast hue but-shikanī meñ \\ ham haiñ to abhī raah meñ hai sañg-e-girāñ aur',
          'har dāġh-e-tāza yak-dil-e-dāġh intizār hai \\ arz-e-fazā-e-sīna-e-dard imtihāñ na pūchh',
          'har ek baat pe kahte ho tum ki tū kyā hai \\ tumhīñ kaho ki ye andāz-e-guftugū kyā hai',
          'har gaam aable se hai dil dar-tah-e-qadam \\ kyā biim ahl-e-dard ko saḳhtī-e-rāh kā',
          'har qadam dūrī-e-manzil hai numāyāñ mujh se \\ merī raftār se bhāge hai bayābāñ mujh se',
          "har rang meñ jalā 'asad'-e-fitna-intizār \\ parvāna-e-tajallī-e-sham-e-zuhūr thā",
          'har-bun-e-mū se dam-e-zikr na Tapke ḳhuuñ naab \\ hamza kā qissa huā ishq kā charchā na huā',
          'har-chand jāñ-gudāzi-e-qahr-o-itāb hai \\ har-chand pusht-e-garmi-e-tāb-o-tavāñ nahīñ',
          'harīf-e-vahshat-e-nāz-e-nasīm-e-ishq jab aa.uuñ \\ ki misl-e-ġhuncha sāz-e-yak-gulistāñ dil muhayyā ho',
          'hasad se dil agar afsurda hai garm-e-tamāshā ho \\ ki chashm-e-tañg shāyad kasrat-e-nazzāra se vā ho',
          'hasrat ne lā rakhā tirī bazm-e-ḳhayāl meñ \\ gul-dasta-e-nigāh suvaidā kaheñ jise',
          'hasrat-e-lazzat-e-āzār rahī jaatī hai \\ jāda-e-rāh-e-vafā juz dam-e-shamshīr nahīñ',
          'hasrat-e-nashsha-e-vahshat na ba-sa.i-e-dil hai \\ arz-e-ḳhamiyāza-e-majnūñ hai garebāñ merā',
          'hastī hamārī apnī fanā par dalīl hai \\ yaañ tak miTe ki aap ham apnī qasam hue',
          "hastī ke mat fareb meñ aa jā.iyo 'asad' \\ aalam tamām halqa-e-dām-e-ḳhayāl hai",
          'havas ko hai nashāt-e-kār kyā kyā \\ na ho marnā to jiine kā mazā kyā',
          'havā-e-par-fishānī barq-e-ḳhirman-hā-e-ḳhātir hai \\ ba-bāl-e-sho.ala-e-betāb hai parvāna-zār ātish',
          'hazrat-e-nāseh gar aaveñ diida o dil farsh-e-rāh \\ koī mujh ko ye to samjhā do ki samajhāveñge kyā',
          'hazāroñ ḳhvāhisheñ aisī ki har ḳhvāhish pe dam nikle \\ bahut nikle mire armān lekin phir bhī kam nikle',
          'hañs ke bulvā.iye miT jā.egā sab dil kā gila \\ kyā tasavvur hai tumhārā ki miTā bhī na sakūñ',
          'hilāl-āsā tahī rah gar kushādan-hā-e-dil chāhe \\ huā mah kasrat-e-sarmāya-andozī se tañg āḳhir',
          'hindostān sāya-e-gul pā-e-taḳht thā \\ jāh-o-jalāl-e-ahd-e-visāl-e-butāñ na pūchh',
          'ho fishār-e-zof meñ kyā nā-tavānī kī numūd \\ qad ke jhukne kī bhī gunjā.ish mire tan meñ nahīñ',
          'ho ga.e haiñ jamā ajzā-e-nigāh-e-āftāb \\ zarre us ke ghar kī dīvāroñ ke rauzan meñ nahīñ',
          'ho liye kyuuñ nāma-bar ke saath saath \\ yā rab apne ḳhat ko ham pahuñchā.eñ kyā',
          'hotā hai nihāñ gard meñ sahrā mire hote \\ ghistā hai jabīñ ḳhaak pe dariyā mire aage',
          "hoñ ḳhamoshī-e-chaman hasrat-e-dīdār 'asad' \\ mizha hai shāna-kash-e-turra-e-guftār hunūz",
          'hujūm-e-nāla hairat ājiz-e-arz yak-afġhāñ hai \\ ḳhamoshī resha-e-sad-nīstāñ se ḳhas-ba-dandāñ hai',
          'hujūm-e-ġham se yaañ tak sar-nigūnī mujh ko hāsil hai \\ ki tār-e-dāman o tār-e-nazar meñ farq mushkil hai',
          "husn aur us pe husn-e-zan rah ga.ī bul-havas kī sharm \\ apne pe e'timād hai ġhair ko āzmā.e kyuuñ",
          'husn ġhamze kī kashākash se chhuTā mere ba.ad \\ baare ārām se haiñ ahl-e-jafā mere ba.ad',
          'husn-e-be-parvā ḳharīdār-e-matā-e-jalva hai \\ aa.ina zānū-e-fikr-e-iḳhtirā-e-jalva hai',
          'husn-e-mah garche ba-hañgām-e-kamāl achchhā hai \\ us se merā mah-e-ḳhurshīd-jamāl achchhā hai',
          'huuñ charāġhān-e-havas juuñ kāġhaz-e-ātish-zada \\ daaġh garm-e-koshish-e-ījād-e-dāġh-e-tāza thā',
          'huuñ giraftār-e-ulfat-e-sayyād \\ varna baaqī hai tāqat-e-parvāz',
          'huuñ tire va.ada na karne meñ bhī raazī ki kabhī \\ gosh minnat-kash-e-gulbāñg-e-tasallī na huā',
          'huuñ za-ḳhud rafta-e-baidā-e-ḳhayāl \\ bhuul jaanā hai nishānī merī',
          'huzūr-e-shāh meñ ahl-e-suḳhan kī āzmā.ish hai \\ chaman meñ ḳhush-navāyan-e-chaman kī āzmā.ish hai',
          'huā hai māne-e-āshiq-navāzī nāz-e-ḳhud-bīnī \\ takalluf-bar-taraf ā.īna-e-tam.īz haa.el hai',
          'huā jab ġham se yuuñ be-his to ġham kyā sar ke kaTne kā \\ na hotā gar judā tan se to zaanū par dharā hotā',
          "huī muddat ki 'ġhālib' mar gayā par yaad aatā hai \\ vo har ik baat par kahnā ki yuuñ hotā to kyā hotā",
          'huī ye kasrat-e-ġham se talaf kaifiyat-e-shādī \\ ki sub.h-e-īd mujh ko bad-tar az-chāk-e-garebāñ hai',
          'ibn-e-mariyam huā kare koī \\ mere dukh kī davā kare koī',
          'ik khel hai aurañg-e-sulaimāñ mire nazdīk \\ ik baat hai ejāz-e-masīhā mire aage',
          'is qadar zabt kahāñ hai kabhī aa bhī na sakūñ \\ sitam itnā to na kiije ki uThā bhī na sakūñ',
          'ishq ke taġhāful se harzah-gard hai aalam \\ rū-e-shash-jihat-āfāq pusht-e-chashm-e-zindāñ hai',
          'ishq kī raah meñ hai charḳh-e-makaukab kī vo chaal \\ sust-rau jaise koī ābla-pā hotā hai',
          'ishq mujh ko nahīñ vahshat hī sahī \\ merī vahshat tirī shohrat hī sahī',
          'ishq se tabī.at ne ziist kā mazā paayā \\ dard kī davā paa.ī dard-e-be-davā paayā',
          'ishrat-e-qatl-gah-e-ahl-e-tamannā mat pūchh \\ īd-e-nazzāra hai shamshīr kā uryāñ honā',
          'ishrat-e-qatra hai dariyā meñ fanā ho jaanā \\ dard kā had se guzarnā hai davā ho jaanā',
          'jaan tum par nisār kartā huuñ \\ maiñ nahīñ jāntā duā kyā hai',
          'jaanā paḌā raqīb ke dar par hazār baar \\ ai kaash jāntā na tire rah-guzar ko maiñ',
          'jaate hue kahte ho qayāmat ko mileñge \\ kyā ḳhuub qayāmat kā hai goyā koī din aur',
          'jaatā huuñ dāġh-e-hasrat-e-hastī liye hue \\ huuñ sham-e-kushta dar-ḳhur-e-mahfil nahīñ rahā',
          'jaatī hai koī kashmakash andoh-e-ishq kī \\ dil bhī agar gayā to vahī dil kā dard thā',
          "jaañ dar-havā-e-yak-nigah-e-garm hai 'asad' \\ parvāna hai vakīl tire dād-ḳhvāh kā",
          'jaañ kyuuñ nikalne lagtī hai tan se dam-e-samā \\ gar vo sadā samā.ī hai chañg o rabāb meñ',
          'jab karam ruḳhsat-e-bebākī-o-gustāḳhī de \\ koī taqsīr ba-juz ḳhajlat-e-taqsīr nahīñ',
          'jab ki tujh bin nahīñ koī maujūd \\ phir ye hañgāma ai ḳhudā kyā hai',
          'jab tak dahān-e-zaḳhm na paidā kare koī \\ mushkil ki tujh se rāh-e-suḳhan vā kare koī',
          "jab tak ki na dekhā thā qad-e-yār kā aalam \\ maiñ mo'taqid-e-fitna-e-mahshar na huā thā",
          'jab vo jamāl-e-dil-faroz sūrat-e-mehr-e-nīm-roz \\ aap hī ho nazāra-soz parde meñ muñh chhupā.e kyuuñ',
          'jahāñ meñ ho ġham-o-shādī baham hameñ kyā kaam \\ diyā hai ham ko ḳhudā ne vo dil ki shaad nahīñ',
          'jale hai dekh ke bālīn-e-yār par mujh ko \\ na kyuuñ ho dil pe mire dāġh-e-bad-gumānī-e-sham.a',
          'jalva az-bas-ki taqāzā-e-nigah kartā hai \\ jauhar-e-ā.ina bhī chāhe hai mizhgāñ honā',
          'jalva zār-e-ātish-e-dozaḳh hamārā dil sahī \\ fitna-e-shor-e-qayāmat kis ke āb-o-gil meñ hai',
          "jalva-e-ḳhur se fanā hotī hai shabnam 'ġhālib' \\ kho diyā satvat-e-asmā-e-jalālī ne mujhe",
          'jalve kā tere vo aalam hai ki gar kiije ḳhayāl \\ dīda-e-dil ko ziyārat-gāh-e-hairānī kare',
          'jalā hai jism jahāñ dil bhī jal gayā hogā \\ kuredte ho jo ab raakh justujū kyā hai',
          'jam.a karte ho kyuuñ raqīboñ ko \\ ik tamāshā huā gila na huā',
          "jarāhat-tohfa almās-armuġhāñ dāġh-e-jigar hadiya \\ mubārakbād 'asad' ġham-ḳhvār-e-jān-e-dardmand aayā",
          'jauhar-e-teġh ba-sar-chashma-e-dīgar mālūm \\ huuñ maiñ vo sabza ki zahrāb ugātā hai mujhe',
          'jaur se baaz aa.e par baaz aa.eñ kyā \\ kahte haiñ ham tujh ko muñh dikhlā.eñ kyā',
          'jazba-e-be-iḳhtiyār-e-shauq dekhā chāhiye \\ sīna-e-shamshīr se bāhar hai dam shamshīr kā',
          'jigar ko mire ishq-e-ḳhūñ-nāba-mashrab \\ likhe hai ḳhudāvand-e-nemat salāmat',
          'jis qadar rūh-e-nabātī hai jigar tishna-e-nāz \\ de hai taskīñ ba-dam-e-āb-e-baqā mauj-e-sharāb',
          'jis zaḳhm kī ho saktī ho tadbīr rafū kī \\ likh dījiyo yā rab use qismat meñ adū kī',
          'jo aa.uuñ sāmne un ke to marhabā na kaheñ \\ jo jā.ūñ vaañ se kahīñ ko to ḳhair-bād nahīñ',
          'jo huā ġharqa-e-mai baḳht-e-rasā rakhtā hai \\ sar se guzre pe bhī hai bāl-e-humā mauj-e-sharāb',
          'jo mudda.ī bane us ke na mudda.ī baniye \\ jo nā-sazā kahe us ko na nā-sazā kahiye',
          'jo munkir-e-vafā ho fareb us pe kyā chale \\ kyuuñ bad-gumāñ huuñ dost se dushman ke baab meñ',
          'jo na naqd-e-dāġh-e-dil kī kare shola pāsbānī \\ to fasurdagī nihāñ hai ba-kamīn-e-be-zabānī',
          'jo thā so mauj-e-rañg ke dhoke meñ mar gayā \\ ai vaa.e nāla-e-lab-e-ḳhūnīñ-navā-e-gul',
          "josh-e-junūñ se kuchh nazar aatā nahīñ 'asad' \\ sahrā hamārī aañkh meñ yak-musht-e-ḳhāk hai",
          'junūñ garm intizār o naala betābī kamand aayā \\ suvaidā tā ba-lab zanjīrī-e-dūd-e-sipand aayā',
          'junūñ kī dast-gīrī kis se ho gar ho na uryānī \\ garebāñ-chāk kā haq ho gayā hai merī gardan par',
          'junūñ tohmat-kash-e-taskīñ na ho gar shādmānī kī \\ namak-pāsh-e-ḳharāsh-e-dil hai lazzat zindagānī kī',
          'juuñ jaada sar-ba-kū-e-tamannā-e-be-dilī \\ zanjīr-e-pā hai rishta-e-hubbul-vatan hunūz',
          'juuñ par-e-tā.ūs jauhar taḳhta mashq-e-rañg hai \\ bas-ki hai vo qibla-e-ā.īna mahv-e-iḳhtirā.a',
          'juz dil surāġh-e-dard ba-dil-ḳhuftagāñ na pūchh \\ ā.īna arz kar ḳhat-o-ḳhāl-e-bayāñ na pūchh',
          'juz naam nahīñ sūrat-e-ālam mujhe manzūr \\ juz vahm nahīñ hastī-e-ashiyā mire aage',
          'juz zaḳhm-e-teġh-e-nāz nahīñ dil meñ aarzū \\ jeb-e-ḳhayāl bhī tire hāthoñ se chaak hai',
          "jā-e-istihzā hai ishrat-koshi-e-hastī 'asad' \\ sub.h o shabnam fursat-e-nashv-o-numā-e-ḳhanda hai",
          'jāda-e-rah ḳhur ko vaqt-e-shām hai tār-e-shuā.a \\ charḳh vā kartā hai māh-e-nau se āġhosh-e-vidā.a',
          'jādād-e-bāda-noshī-e-rindāñ hai shash-jihat \\ ġhāfil gumāñ kare hai ki getī ḳharāb hai',
          'jāntā huuñ savāb-e-tā.at-o-zohd \\ par tabī.at idhar nahīñ aatī',
          'jī meñ hī kuchh nahīñ hai hamāre vagarna ham \\ sar jaa.e yā rahe na raheñ par kahe baġhair',
          'kaTe to shab kaheñ kaaTe to saañp kahlāve \\ koī batāo ki vo zulf-e-ḳham-ba-ḳham kyā hai',
          'kaam us se aa paḌā hai ki jis kā jahān meñ \\ leve na koī naam sitamgar kahe baġhair',
          'kaav kāv-e-saḳht-jānī hā.e-tanhā.ī na pūchh \\ sub.h karnā shaam kā laanā hai jū-e-shīr kā',
          'kab se huuñ kyā batā.ūñ jahān-e-ḳharāb meñ \\ shab-hā-e-hijr ko bhī rakhūñ gar hisāb meñ',
          'kab vo suntā hai kahānī merī \\ aur phir vo bhī zabānī merī',
          'kabhī jo yaad bhī aatā huuñ maiñ to kahte haiñ \\ ki aaj bazm meñ kuchh fitna-o-fasād nahīñ',
          'kabhī nekī bhī us ke jī meñ gar aa jaa.e hai mujh se \\ jafā.eñ kar ke apnī yaad sharmā jaa.e hai mujh se',
          'kabhī to is dil-e-shorīda kī bhī daad mile \\ ki ek umr se hasrat-parast-e-bālīñ hai',
          'kahte haiñ jab rahī na mujhe tāqat-e-suḳhan \\ jānūñ kisī ke dil kī maiñ kyūñkar kahe baġhair',
          'kahte ho na deñge ham dil agar paḌā paayā \\ dil kahāñ ki gum kiije ham ne mudda.ā paayā',
          'kahtā hai kaun nāla-e-bulbul ko be-asar \\ parde meñ gul ke laakh jigar chaak ho ga.e',
          "kahtā thā kal vo mahram-e-rāz apne se ki aah \\ dard-e-judā.i-e-'asad'-ullāh-ḳhāñ na pūchh",
          'kahāñ ham bhī rag-o-pai rakhte haiñ insāf bahattar hai \\ na khīñche tāqat-e-ḳhamyāza tohmat nā-tavānī kī',
          'kahūñ jo haal to kahte ho mudda.ā kahiye \\ tumhīñ kaho ki jo tum yuuñ kaho to kyā kahiye',
          "kahūñ kyā ḳhūbi-e-auzā-e-abnā-e-zamāñ 'ġhālib' \\ badī kī us ne jis se ham ne kī thī bār-hā nekī",
          'kal ke liye kar aaj na ḳhissat sharāb meñ \\ ye sū-e-zan hai sāqi-e-kausar ke baab meñ',
          'kam nahīñ nāzish-e-hamnāmi-e-chashm-e-ḳhūbāñ \\ terā bīmār burā kyā hai gar achchhā na huā',
          'kare hai baada tire lab se kasb-e-rañg-e-faroġh \\ ḳhat-e-piyāla sarāsar nigāh-e-gul-chīñ hai',
          'kare hai sarf ba-īmā-e-sho.ala qissa tamām \\ ba-tarz-e-ahl-e-fanā hai fasāna-ḳhvānī-e-sham.a',
          'kareñge kohkan ke hausle kā imtihān āḳhir \\ abhī us ḳhasta ke nirū-e-tan kī āzmā.ish hai',
          'kartā huuñ jam.a phir jigar-e-laḳht-laḳht ko \\ arsa huā hai dāvat-e-mizhgāñ kiye hue',
          'kashākash-hā-e-hastī se kare kyā sa.i-e-āzādī \\ hui zanjīr-e-mauj-e-āb ko fursat ravānī kī',
          'khulegā kis tarah mazmūñ mire maktūb kā yā-rab \\ qasam khaa.ī hai us kāfir ne kāġhaz ke jalāne kī',
          'kis ko sunā.ūñ hasrat-e-iz.hār kā gila \\ dil fard-e-jama-o-ḳharch zabāñ-hā-e-lāl hai',
          'kis muñh se shukr kījiye is lutf-e-ḳhās kā \\ pursish hai aur pā-e-suḳhan darmiyāñ nahīñ',
          'kis parde meñ hai ā.ina-pardāz ai ḳhudā \\ rahmat ki uzr-ḳhvāh-e-lab-e-be-savāl hai',
          'kis se mahrūmī-e-qismat kī shikāyat kiije \\ ham ne chāhā thā ki mar jaa.eñ so vo bhī na huā',
          'kis vāste aziiz nahīñ jānte mujhe \\ la.al o zamurrad o zar o gauhar nahīñ huuñ maiñ',
          'kitne shīrīñ haiñ tere lab ki raqīb \\ gāliyāñ khā ke be-mazā na huā',
          'koh ke hoñ bār-e-ḳhātir gar sadā ho jā.iye \\ be-takalluf ai sharār-e-jasta kyā ho jā.iye',
          "kohkan naqqāsh-e-yak-timsāl-e-shīrīñ thā 'asad' \\ sañg se sar maar kar hove na paidā āshnā",
          'koī kahe ki shab-e-mah meñ kyā burā.ī hai \\ balā se aaj agar din ko abr o baad nahīñ',
          'koī mere dil se pūchhe tire tīr-e-nīm-kash ko \\ ye ḳhalish kahāñ se hotī jo jigar ke paar hotā',
          'koī ummīd bar nahīñ aatī \\ koī sūrat nazar nahīñ aatī',
          'kulfat-e-afsurdagī ko aish-e-betābī harām \\ varna dandāñ dar dil afshurdan binā-e-ḳhanda hai',
          'kyuuñ Darte ho ushshāq kī be-hauslagī se \\ yaañ to koī suntā nahīñ fariyād kisū kī',
          'kyuuñ gardish-e-mudām se ghabrā na jaa.e dil \\ insān huuñ piyāla o sāġhar nahīñ huuñ maiñ',
          'kyuuñ huā thā taraf-e-ābla-e-pā yā-rab \\ jaada hai vā-shudan-e-pechish-e-tūmār hunūz',
          'kyuuñ jal gayā na tāb-e-ruḳh-e-yār dekh kar \\ jaltā huuñ apnī tāqat-e-dīdār dekh kar',
          'kyuuñ na Thahreñ hadaf-e-nāvak-e-bedād ki ham \\ aap uThā laate haiñ gar tiir ḳhatā hotā hai',
          'kyuuñ na ho be-iltifātī us kī ḳhātir jam.a hai \\ jāntā hai mahv-e-pursish-hā-e-pinhānī mujhe',
          'kyā bayāñ kar ke mirā ro.eñge yaar \\ magar āshufta-bayānī merī',
          'kyā kahūñ tārīki-e-zindān-e-ġham andher hai \\ pamba nūr-e-sub.h se kam jis ke rauzan meñ nahīñ',
          'kyā sham.a ke nahīñ haiñ havā-ḳhvāh bazm meñ \\ ho ġham hī jāñ-gudāz to ġham-ḳhvār kyā kareñ',
          'kyā ta.ajjub hai jo us ko dekh kar aa jaa.e rahm \\ vaañ talak koī kisī hiile se pahuñchā de mujhe',
          'kyā ābrū-e-ishq jahāñ aam ho jafā \\ ruktā huuñ tum ko be-sabab āzār dekh kar',
          'kār-gāh-e-hastī meñ laala dāġh-sāmāñ hai \\ barq-e-ḳhirman-e-rāhat ḳhūn-e-garm-e-dahqāñ hai',
          'kār-ḳhāne se junūñ ke bhī maiñ uryāñ niklā \\ merī qismat kā na ek-ādh garebāñ niklā',
          'kī vafā ham se to ġhair is ko jafā kahte haiñ \\ hotī aa.ī hai ki achchhoñ ko burā kahte haiñ',
          'laag ho to us ko ham samjheñ lagāo \\ jab na ho kuchh bhī to dhokā khā.eñ kyā',
          'lag ga.ī aag agar ghar ko to andesha kyā \\ sho.ala-e-dil to nahīñ hai ki bujhā bhī na sakūñ',
          'lakad kūb-e-havādis kā tahammul kar nahīñ saktī \\ mirī tāqat ki zāmin thī butoñ kī naaz uThāne kī',
          'laraztā hai mirā dil zahmat-e-mehr-e-daraḳhshāñ par \\ maiñ huuñ vo qatra-e-shabnam ki ho ḳhār-e-bayābāñ par',
          'laḳht-e-jigar se hai rag-e-har-ḳhār shāḳh-e-gul \\ tā chand bāġh-bāni-e-sahrā kare koī',
          'le ga.ī saaqī kī naḳhvat qulzum-āshāmī mirī \\ mauj-e-mai kī aaj rag miinā kī gardan meñ nahīñ',
          'le to luuñ sote meñ us ke paañv kā bosa magar \\ aisī bātoñ se vo kāfir bad-gumāñ ho jā.egā',
          'letā na agar dil tumheñ detā koī dam chain \\ kartā jo na martā koī din āh-o-fuġhāñ aur',
          'likhā kare koī ahkām-e-tāla-e-maulūd \\ kise ḳhabar hai ki vaañ jumbish-e-qalam kyā hai',
          'likhī yāroñ kī bad-mastī ne maiḳhāne kī pāmālī \\ hui qatra-fishānī-hā-e-mai-bārān-e-sañg āḳhir',
          'lipaTnā parniyāñ meñ shola-e-ātish kā pinhāñ hai \\ vale mushkil hai hikmat dil meñ soz-e-ġham chhupāne kī',
          'lo ham marīz-e-ishq ke bīmār-dār haiñ \\ achchhā agar na ho to masīhā kā kyā ilaaj',
          'lo vo bhī kahte haiñ ki ye be-nañg-o-nām hai \\ ye jāntā agar to luTātā na ghar ko maiñ',
          'logoñ ko hai ḳhurshīd-e-jahāñ-tāb kā dhokā \\ har roz dikhātā huuñ maiñ ik dāġh-e-nihāñ aur',
          "luuñ vaam baḳht-e-ḳhufta se yak-ḳhvāb-e-ḳhush vale \\ 'ġhālib' ye ḳhauf hai ki kahāñ se adā karūñ",
          'lāf-e-tamkīñ fareb-e-sāda-dilī \\ ham haiñ aur rāz-hā-e-sīna-gudāz',
          'lākhoñ lagāo ek churānā nigāh kā \\ lākhoñ banāv ek bigaḌnā itaab meñ',
          'lāzim thā ki dekho mirā rastā koī din aur \\ tanhā ga.e kyuuñ ab raho tanhā koī din aur',
          'lāġhar itnā huuñ ki gar tū bazm meñ jā de mujhe \\ merā zimma dekh kar gar koī batlā de mujhe',
          'magar likhvā.e koī us ko ḳhat to ham se likhvā.e \\ huī sub.h aur ghar se kaan par rakh kar qalam nikle',
          'mah-e-aḳhtar-fashāñ kī bahr istiqbāl āñkhoñ se \\ tamāshā kishvar-e-ā.īna meñ ā.īna-band aayā',
          'mai se ġharaz nashāt hai kis rū-siyāh ko \\ ik-gūna be-ḳhudī mujhe din raat chāhiye',
          'mai vo kyuuñ bahut piite bazm-e-ġhair meñ yā rab \\ aaj hī huā manzūr un ko imtihāñ apnā',
          'mai-e-ishrat kī ḳhvāhish sāqi-e-gardūñ se kyā kiije \\ liye baiThā hai ik do chaar jām-e-vāzh-gūñ vo bhī',
          'mai-kada gar chashm-e-mast-e-nāz se paave shikast \\ mū-e-shīsha dīda-e-sāġhar kī mizhgānī kare',
          'mai-parastāñ ḳhum-e-mai muñh se lagā.e hī bane \\ ek din gar na huā bazm meñ saaqī na sahī',
          'mai-ḳhāna-e-jigar meñ yahāñ ḳhaak bhī nahīñ \\ ḳhamyāza khīñche hai but-e-be-dād-fan hunūz',
          'maiñ adam se bhī pare huuñ varna ġhāfil bār-hā \\ merī āh-e-ātishīñ se bāl-e-anqā jal gayā',
          'maiñ aur ek aafat kā TukḌā vo dil-e-vahshī ki hai \\ āfiyat kā dushman aur āvārgī kā āshnā',
          'maiñ aur hazz-e-vasl ḳhudā-sāz baat hai \\ jaañ nazr denī bhuul gayā iztirāb meñ',
          'maiñ aur sad-hazār navā-e-jigar-ḳharāsh \\ tū aur ek vo nā-shunīdan ki kyā kahūñ',
          'maiñ bhī muñh meñ zabān rakhtā huuñ \\ kaash pūchho ki mudda.ā kyā hai',
          'maiñ muztarib huuñ vasl meñ ḳhauf-e-raqīb se \\ Daalā hai tum ko vahm ne kis pech-o-tāb meñ',
          'maiñ ne chāhā thā ki andoh-e-vafā se chhūTūñ \\ vo sitamgar mire marne pe bhī raazī na huā',
          "maiñ ne maanā ki kuchh nahīñ 'ġhālib' \\ muft haath aa.e to burā kyā hai",
          'maiñ nā-murād dil kī tasallī ko kyā karūñ \\ maanā ki tere ruḳh se nigah kāmyāb hai',
          'maiñ sāda-dil āzurdagi-e-yār se ḳhush huuñ \\ ya.anī sabaq-e-shauq mukarrar na huā thā',
          'maiñ unheñ chheḌūñ aur kuchh na kaheñ \\ chal nikalte jo mai piye hote',
          'majbūrī o dāvā-e-giraftāri-e-ulfat \\ dast-e-tah-e-sañg-āmda paimān-e-vafā hai',
          'mansab-e-sheftagī ke koī qābil na rahā \\ huī māzūli-e-andāz-o-adā mere ba.ad',
          'manzar ik bulandī par aur ham banā sakte \\ arsh se udhar hotā kaash ke makāñ apnā',
          'maqtal ko kis nashāt se jaatā huuñ maiñ ki hai \\ pur-gul ḳhayāl-e-zaḳhm se dāman nigāh kā',
          "mar gayā sadma-e-yak-jumbish-e-lab se 'ġhālib' \\ nā-tavānī se harīf-e-dam-e-īsī na huā",
          'marham kī justujū meñ phirā huuñ jo duur duur \\ tan se sivā figār haiñ is ḳhasta-tan ke paañv',
          'marne kī ai dil aur hī tadbīr kar ki maiñ \\ shāyān-e-dast-o-bāzū-e-qātil nahīñ rahā',
          'martā huuñ is āvāz pe har chand sar uḌ jaa.e \\ jallād ko lekin vo kahe jaa.eñ ki haañ aur',
          'masjid ke zer-e-sāya ḳharābāt chāhiye \\ bhauñ paas aañkh qibla-e-hājāt chāhiye',
          'mastī ba-zauq-e-ġhaflat-e-sāqī halāk hai \\ mauj-e-sharāb yak-mizha-e-ḳhvāb-nāk hai',
          'mat pūchh ki kyā haal hai merā tire pīchhe \\ tū dekh ki kyā rañg hai terā mire aage',
          'mauj-e-ḳhūñ sar se guzar hī kyuuñ na jaa.e \\ āstān-e-yār se uTh jaa.eñ kyā',
          'maut kā ek din muayyan hai \\ niind kyuuñ raat bhar nahīñ aatī',
          'mehrbāñ ho ke bulā lo mujhe chāho jis vaqt \\ maiñ gayā vaqt nahīñ huuñ ki phir aa bhī na sakūñ',
          'mere hone meñ hai kyā rusvā.ī \\ ai vo majlis nahīñ ḳhalvat hī sahī',
          'mere ġham-ḳhāne kī qismat jab raqam hone lagī \\ likh diyā min-jumla-e-asbāb-e-vīrānī mujhe',
          'merī qismat meñ ġham gar itnā thā \\ dil bhī yā-rab ka.ī diye hote',
          'miT jā.egā sar gar tirā patthar na ghisegā \\ huuñ dar pe tire nāsiya-farsā koī din aur',
          'miltī hai ḳhū-e-yār se naar iltihāb meñ \\ kāfir huuñ gar na miltī ho rāhat azaab meñ',
          "mire dil meñ hai 'ġhālib' shauq-e-vasl o shikva-e-hijrāñ \\ ḳhudā vo din kare jo us se maiñ ye bhī kahūñ vo bhī",
          'mirī hastī fazā-e-hairat ābād-e-tamannā hai \\ jise kahte haiñ naala vo usī aalam kā anqā hai',
          'misāl ye mirī koshish kī hai ki murġh-e-asīr \\ kare qafas meñ farāham ḳhas āshiyāñ ke liye',
          'mudda.ā mahv-e-tamāshā-e-shikast-e-dil hai \\ ā.ina-ḳhāna meñ koī liye jaatā hai mujhe',
          'muddat huī hai yaar ko mehmāñ kiye hue \\ josh-e-qadah se bazm charāġhāñ kiye hue',
          'mujh ko dayār-e-ġhair meñ maarā vatan se duur \\ rakh lī mire ḳhudā ne mirī bekasī kī sharm',
          'mujh ko pūchhā to kuchh ġhazab na huā \\ maiñ ġharīb aur tū ġharīb-navāz',
          'mujh tak kab un kī bazm meñ aatā thā daur-e-jām \\ saaqī ne kuchh milā na diyā ho sharāb meñ',
          'mujhe ab dekh kar abr-e-shafaq-ālūda yaad aayā \\ ki furqat meñ tirī ātish barastī thī gulistāñ par',
          'mujhe us se kyā tavaqqo ba-zamāna-e-javānī \\ kabhī kūdkī meñ jis ne na sunī mirī kahānī',
          'munhasir marne pe ho jis kī umiid \\ nā-umīdī us kī dekhā chāhiye',
          'mushkīñ libās-e-kāba alī ke qadam se jaan \\ nāf-e-zamīn hai na ki nāf-e-ġhazāl hai',
          'mutaqābil hai muqābil merā \\ ruk gayā dekh ravānī merī',
          "muñd ga.iiñ kholte hī kholte āñkheñ 'ġhālib' \\ yaar laa.e mirī bālīñ pe use par kis vaqt",
          'muñh na dikhlāve na dikhlā par ba-andāz-e-itāb \\ khol kar parda zarā āñkheñ hī dikhlā de mujhe',
          'māna-e-dasht-navardī koī tadbīr nahīñ \\ ek chakkar hai mire paañv meñ zanjīr nahīñ',
          'māna-e-vahshat-ḳhirāmī-hā-e-lailā kaun hai \\ ḳhāna-e-majnūn-e-sahrā-gard be-darvāza thā',
          'mīnā-e-mai hai sarv nashāt-e-bahār se \\ bāl-e-tadrav jalva-e-mauj-e-sharāb hai',
          'na auroñ kī suntā na kahtā huuñ apnī \\ sar-e-ḳhasta dushvār-e-vahshat salāmat',
          'na chhoḌī hazrat-e-yūsuf ne yaañ bhī ḳhāna-ārā.ī \\ safedī dīda-e-yāqūb kī phirtī hai zindāñ par',
          'na gul-e-naġhma huuñ na parda-e-sāz \\ maiñ huuñ apnī shikast kī āvāz',
          'na hashr-o-nashr kā qaa.el na kesh o millat kā \\ ḳhudā ke vāste aise kī phir qasam kyā hai',
          'na ho husn-e-tamāshā-dost rusvā bevafā.ī kā \\ ba-mohr-e-sad-nazar sābit hai da.avā pārsā.ī kā',
          'na huī gar mire marne se tasallī na sahī \\ imtihāñ aur bhī baaqī ho to ye bhī na sahī',
          'na itnā burrish-e-teġh-e-jafā par naaz farmāo \\ mire dariyā-e-be-tābī meñ hai ik mauj-e-ḳhūñ vo bhī',
          'na jānūñ kyūñki miTe dāġh-e-ta.an-e-bad-ahdī \\ tujhe ki aa.ina bhī varta-e-malāmat hai',
          'na kahiyo ta.an se phir tum ki ham sitamgar haiñ \\ mujhe to ḳhū hai ki jo kuchh kaho bajā kahiye',
          'na kartā kaash naala mujh ko kyā mālūm thā hamdam \\ ki hogā bā.is-e-afzā.ish-e-dard-e-darūñ vo bhī',
          'na khīñch ai sa.ī-e-dast-e-nā-rasā zulf-e-tamannā ko \\ pareshāñ-tar hai mū-e-ḳhāma se tadbīr maanī kī',
          'na kī sāmān-e-aish-o-jāh ne tadbīr vahshat kī \\ huā jām-e-zumurrad bhī mujhe dāġh-e-palañg āḳhir',
          'na laa.ī shoḳhi-e-andesha tāb-e-rañj-e-naumīdī \\ kaf-e-afsos milnā ahd-e-tajdīd-e-tamannā hai',
          'na leve gar ḳhas-e-jauhar tarāvat sabza-e-ḳhat se \\ lagā.e ḳhāna-e-ā.īna meñ rū-e-nigār ātish',
          'na maarā jaan kar be-jurm ġhāfil terī gardan par \\ rahā mānind-e-ḳhūn-e-be-gunah haq āshnā.ī kā',
          'na pūchh nusḳha-e-marham jarāhat-e-dil kā \\ ki us meñ reza-e-almās juzv-e-āzam hai',
          'na pūchh sīna-e-āshiq se āb-e-teġh-e-nigāh \\ ki zaḳhm-e-rauzan-e-dar se havā nikaltī hai',
          'na sho.ale meñ ye karishma na barq meñ ye adā \\ koī batāo ki vo shoḳh-e-tund-ḳhū kyā hai',
          'na sove ābloñ meñ gar sirishk-e-dīda-e-nam se \\ ba-jaulāñ-gāh-e-naumīdī nigāh-e-ājizāñ pā hai',
          'na thā kuchh to ḳhudā thā kuchh na hotā to ḳhudā hotā \\ Duboyā mujh ko hone ne na hotā maiñ to kyā hotā',
          'naala sarmāya-e-yak-ālam o aalam kaf-e-ḳhāk \\ āsmāñ baiza-e-quamrī nazar aatā hai mujhe',
          'naam kā mere hai jo dukh ki kisī ko na milā \\ kaam meñ mere hai jo fitna ki barpā na huā',
          'nafas mauj-e-muhīt-e-be-ḳhudī hai \\ taġhāful-hā-e-sāqī kā gila kyā',
          'nafas-e-qais ki hai chashm-o-charāġh-e-sahrā \\ gar nahīñ sham-e-siyah-ḳhāna-e-lailī na sahī',
          'nahīñ barq-o-sharar juz vahshat-e-zabt-e-tapīdan-hā \\ bilā gardān-e-be-parvā ḳharāmī-hā-e-yār ātish',
          'nahīñ dil meñ mire vo qatra-e-ḳhūñ \\ jis se mizhgāñ huī na ho gul-bāz',
          'nahīñ gar ba-kām-e-dil-e-ḳhasta gardūñ \\ jigar-ḳhāī-e-josh-e-hasrat salāmat',
          'nahīñ gar sar-o-barg-e-idrāk-e-ma.anī \\ tamāshā-e-nairañg-e-sūrat salāmat',
          'nahīñ iqlīm-e-ulfat meñ koī tūmār-e-nāz aisā \\ ki pusht-e-chashm se jis kī na hove mohr unvāñ par',
          "nahīñ ki mujh ko qayāmat kā e'tiqād nahīñ \\ shab-e-firāq se roz-e-jazā ziyād nahīñ",
          'nahīñ kuchh sub.ha-o-zunnār ke phande meñ gīrā.ī \\ vafādārī meñ shaiḳh o barhaman kī āzmā.ish hai',
          'nahīñ zarīya-e-rāhat jarāhat-e-paikāñ \\ vo zaḳhm-e-teġh hai jis ko ki dil-kushā kahiye',
          'naqsh fariyādī hai kis kī shoḳhi-e-tahrīr kā \\ kāġhzī hai pairahan har paikar-e-tasvīr kā',
          'naqsh-e-ibrat dar nazar yā naqd-e-ishrat dar bisāt \\ do-jahāñ vus.at ba-qadr-e-yak-fa.zā-e-ḳhanda hai',
          'nashsha-e-mai be-chaman dūd-e-charāġh-e-kushta hai \\ jaam dāġh-e-shola-andūd-e-charāġh-e-kushta hai',
          'nashsha-e-rañg se hai vāshud-e-gul \\ mast kab band-e-qabā bāñdhte haiñ',
          "nashv-o-numā hai asl se 'ġhālib' furūa ko \\ ḳhāmoshī hī se nikle hai jo baat chāhiye",
          'nashāt-e-dāġh-e-ġham-e-ishq kī bahār na pūchh \\ shaguftagī hai shahīd-e-gul-e-ḳhizānī-e-sham.a',
          'nasīm-e-misr ko kyā pīr-e-kan.āñ kī havā-ḳhvāhī \\ use yūsuf kī bū-e-pairahan kī āzmā.ish hai',
          'naved-e-amn hai bedād-e-dost jaañ ke liye \\ rahī na tarz-e-sitam koī āsmāñ ke liye',
          'navāzish-hā-e-bejā dekhtā huuñ \\ shikāyat-hā-e-rañgīñ kā gila kyā',
          'nazar lage na kahīñ us ke dast-o-bāzū ko \\ ye log kyuuñ mire zaḳhm-e-jigar ko dekhte haiñ',
          'nazzāra kyā harīf ho us barq-e-husn kā \\ josh-e-bahār jalve ko jis ke naqāb hai',
          'nazzāre ne bhī kaam kiyā vaañ naqāb kā \\ mastī se har nigah tire ruḳh par bikhar ga.ī',
          'nigāh-e-be-mahābā chāhtā huuñ \\ taġhāful-hā-e-tamkīñ-āzmā kyā',
          'nikalnā ḳhuld se aadam kā sunte aa.e haiñ lekin \\ bahut be-ābrū ho kar tire kūche se ham nikle',
          'nikaltī hai tapish meñ bismiloñ kī barq kī shoḳhī \\ ġharaz ab tak ḳhayāl-e-garmī-e-raftār qātil hai',
          'nā-chār bekasī kī bhī hasrat uThā.iye \\ dushvāri-e-rah-o-sitam-e-ham-rahāñ na pūchh',
          'nākāmi-e-nigāh hai barq-e-nazārā-soz \\ tū vo nahīñ ki tujh ko tamāshā kare koī',
          'nāla-e-dil ne diye aurāq-e-laḳht-e-dil ba-bād \\ yād-gār-e-nāla ik dīvān-e-be-shīrāza thā',
          'ohde se mad.h-e-nāz ke bāhar na aa sakā \\ gar ik adā ho to use apnī qazā kahūñ',
          'pa.e-nazr-e-karam tohfa hai sharm-e-nā-rasā.ī kā \\ ba-ḳhūñ-ġhaltīda-e-sad-rañg da.avā pārsā.ī kā',
          'paate nahīñ jab raah to chaḌh jaate haiñ naale \\ ruktī hai mirī tab.a to hotī hai ravāñ aur',
          "pahlū-tahī na kar ġham-o-andoh se 'asad' \\ dil vaqf-e-dard kar ki faqīroñ kā maal hai",
          'paikar-e-ushshāq sāz-e-tāla-e-nā-sāz hai \\ naala goyā gardish-e-saiyyāra kī āvāz hai',
          'panāve be-gudāz-e-mom rabt-e-paikar-ārā.ī \\ nikāle kyā nihāl-e-sham.a be-tuḳhm-e-sharār ātish',
          'pas-az-murdan bhī dīvāna ziyārat-gāh-e-tiflāñ hai \\ sharār-e-sañg ne turbat pe merī gul-fishānī kī',
          'paḌiye gar bīmār to koī na ho tīmārdār \\ aur agar mar jā.iye to nauha-ḳhvāñ koī na ho',
          'phir garm-nāla-hā-e-sharar-bār hai nafas \\ muddat huī hai sair-e-charāġhāñ kiye hue',
          'phir huā vaqt ki ho bāl-kushā mauj-e-sharāb \\ de bat-e-mai ko dil-o-dast-e-shanā mauj-e-sharāb',
          'phir jigar khodne lagā nāḳhun \\ āmad-e-fasl-e-lāla-kārī hai',
          'phir kuchh ik dil ko be-qarārī hai \\ siina juyā-e-zaḳhm-e-kārī hai',
          'phir mujhe dīda-e-tar yaad aayā \\ dil jigar tishna-e-faryād aayā',
          'phir vaz-e-ehtiyāt se rukne lagā hai dam \\ barsoñ hue haiñ chaak garebāñ kiye hue',
          'phūñkā hai kis ne gosh-e-mohabbat meñ ai ḳhudā \\ afsūn-e-intizār tamannā kaheñ jise',
          'pinhāñ thā daam saḳht qarīb āshiyān ke \\ uḌne na paa.e the ki giraftār ham hue',
          'pur huuñ maiñ shikve se yuuñ raag se jaise baajā \\ ik zarā chheḌiye phir dekhiye kyā hotā hai',
          'pīnas meñ guzarte haiñ jo kūche se vo mere \\ kandhā bhī kahāroñ ko badalne nahīñ dete',
          'pūchh mat rusvā.i-e-andāz-e-istiġhnā-e-husn \\ dast marhūn-e-hinā ruḳhsār rahn-e-ġhāza thā',
          'pūchh mat vaj.h-e-siyah-mastī-e-arbāb-e-chaman \\ sāya-e-tāk meñ hotī hai havā mauj-e-sharāb',
          'pūchhe hai kyā vajūd o adam ahl-e-shauq kā \\ aap apnī aag ke ḳhas-o-ḳhāshāk ho ga.e',
          'qad o gesū meñ qais o kohkan kī āzmā.ish hai \\ jahāñ ham haiñ vahāñ dār-o-rasan kī āzmā.ish hai',
          'qahr ho yā balā ho jo kuchh ho \\ kaash ke tum mire liye hote',
          "qaid-e-hastī se rihā.ī mā'lūm \\ ashk ko be-sar-o-pā bāñdhte haiñ",
          'qaid-e-hayāt o band-e-ġham asl meñ donoñ ek haiñ \\ maut se pahle aadmī ġham se najāt paa.e kyuuñ',
          'qat.a kiije na ta.alluq ham se \\ kuchh nahīñ hai to adāvat hī sahī',
          'qatra qatra ik hayūlā hai na.e nāsūr kā \\ ḳhuuñ bhī zauq-e-dard se fāriġh mire tan meñ nahīñ',
          'qibala-e-maqsad-e-nigāh-e-niyāz \\ phir vahī parda-e-amārī hai',
          'qumrī kaf-e-ḳhākistar o bulbul qafas-e-rañg \\ ai naala nishān-e-jigar-e-soḳhta kyā hai',
          'qāsid ke aate aate ḳhat ik aur likh rakhūñ \\ maiñ jāntā huuñ jo vo likheñge javāb meñ',
          'qāsid ko apne haath se gardan na māriye \\ us kī ḳhatā nahīñ hai ye merā qusūr thā',
          'raat din gardish meñ haiñ saat āsmāñ \\ ho rahegā kuchh na kuchh ghabrā.eñ kyā',
          'raat pī zamzam pe mai aur sub.h-dam \\ dho.e dhabbe jāma-e-ehrām ke',
          'raftār-e-umr qat-e-rah-e-iztirāb hai \\ is saal ke hisāb ko barq āftāb hai',
          'rafū-e-zaḳhm se matlab hai lazzat zaḳhm-e-sozan kī \\ samajhiyo mat ki pās-e-dard se dīvāna ġhāfil hai',
          'rahe dil hī meñ tiir achchhā jigar ke paar ho behtar \\ ġharaz shust-e-but-e-nāvak-fagan kī āzmā.ish hai',
          'rahe hai yuuñ gah-o-be-gah ki kū-e-dost ko ab \\ agar na kahiye ki dushman kā ghar hai kyā kahiye',
          'rahe us shoḳh se āzurda ham chande takalluf se \\ takalluf bartaraf thā ek andāz-e-junūñ vo bhī',
          'rahiye ab aisī jagah chal kar jahāñ koī na ho \\ ham-suḳhan koī na ho aur ham-zabāñ koī na ho',
          'rahm kar zālim ki kyā būd-e-charāġh-e-kushta hai \\ nabz-e-bīmār-e-vafā dūd-e-charāġh-e-kushta hai',
          'rahmat agar qubūl kare kyā ba.iid hai \\ sharmindagī se uzr na karnā gunāh kā',
          'rahā balā meñ bhī maiñ mubtala-e-āfat-e-rashk \\ balā-e-jāñ hai adā terī ik jahāñ ke liye',
          'rahā gar koī tā-qayāmat salāmat \\ phir ik roz marnā hai hazrat-salāmat',
          'ranjish-e-hairat-sarishtāñ sīna-sāfī peshkash \\ jauhar-e-ā.īna hai yaañ gard-e-maidān-e-nazā.a',
          'rashk kahtā hai ki us kā ġhair se iḳhlās haif \\ aql kahtī hai ki vo be-mehr kis kā āshnā',
          'rau meñ hai raḳhsh-e-umr kahāñ dekhiye thame \\ ne haath baag par hai na pā hai rikāb meñ',
          'raunaq-e-hastī hai ishq-e-ḳhāna vīrāñ saaz se \\ anjuman be-shamā hai gar barq ḳhirman meñ nahīñ',
          'rañj-e-naumīdi-e-jāved gavārā rahiyo \\ ḳhush huuñ gar nāla-zabūnī kash-e-tāsīr nahīñ',
          'rañj-e-rah kyuuñ khīñchiye vāmāndagī ko ishq hai \\ uTh nahīñ saktā hamārā jo qadam manzil meñ hai',
          'rone se ai nadīm malāmat na kar mujhe \\ āḳhir kabhī to uqda-e-dil vā kare koī',
          'rone se aur ishq meñ bebāk ho ga.e \\ dho.e ga.e ham itne ki bas paak ho ga.e',
          'rusvā-e-dahr go hue āvārgī se tum \\ baare tabī.atoñ ke to chālāk ho ga.e',
          'ruḳh-e-nigār se hai soz-e-jāvidānī-e-sham.a \\ huī hai ātish-e-gul āb-e-zindagānī-e-sham.a',
          'ruḳhsat-e-nāla mujhe de ki mabādā zālim \\ tere chehre se ho zāhir ġham-e-pinhāñ merā',
          'saaf hai az bas-ki aks-e-gul se gulzār-e-chaman \\ jānashīn-e-jauhar-e-ā.īna hai ḳhār-e-chaman',
          'sab ke dil meñ hai jagah terī jo tū raazī huā \\ mujh pe goyā ik zamāna mehrbāñ ho jā.egā',
          'sab ko maqbūl hai da.avā tirī yaktā.ī kā \\ rū-ba-rū koī but-e-ā.ina-sīmā na huā',
          'sabr aur ye adā ki dil aave asīr-e-chāk \\ dard aur ye kamīñ ki rah-e-nāla vā karūñ',
          'sabza-e-ḳhat se tirā kākul-e-sarkash na dabā \\ ye zamurrad bhī harīf-e-dam-e-af.ī na huā',
          "sad-haif vo nākām ki ik umr se 'ġhālib' \\ hasrat meñ rahe ek but-e-arbada-jū kī",
          'safā-e-hairat-e-ā.īna hai sāmān-e-zang āḳhir \\ taġhayyur āb-e-bar-jā-māñda kā paatā hai rañg āḳhir',
          "samajh is fasl meñ kotāhi-e-nashv-o-numā 'ġhālib' \\ agar gul sarv ke qāmat pe pairāhan na ho jaave",
          'samajh ke karte haiñ bāzār meñ vo pursish-e-hāl \\ ki ye kahe ki sar-e-rahguzar hai kyā kahiye',
          'sar khujātā hai jahāñ zaḳhm-e-sar achchhā ho jaa.e \\ lazzat-e-sañg ba-andāza-e-taqrīr nahīñ',
          'sar par hujūm-e-dard-e-ġharībī se Dāliye \\ vo ek musht-e-ḳhāk ki sahrā kaheñ jise',
          'sar-navisht-e-iztirāb-anjāmi-e-ulfat na pūchh \\ nāl-e-ḳhāma ḳhār-ḳhār-e-ḳhātir-e-āġhāz hai',
          'sarf-e-bahā-e-mai hue ālāt-e-mai-kashī \\ the ye hī do hisāb so yuuñ paak ho ga.e',
          'satvat se tere jalva-e-husn-e-ġhuyūr kī \\ ḳhuuñ hai mirī nigāh meñ rañg-e-adā-e-gul',
          'sau baar band-e-ishq se āzād ham hue \\ par kyā kareñ ki dil hī adū hai farāġh kā',
          'saḳhtī kashān-e-ishq kī pūchhe hai kyā ḳhabar \\ vo log rafta rafta sarāpā alam hue',
          'shab ko kisī ke ḳhvāb meñ aayā na ho kahīñ \\ dukhte haiñ aaj us but-e-nāzuk-badan ke paañv',
          'shab ḳhumār-e-shauq-e-sāqī rustaḳhez-andāza thā \\ tā-muhīt-e-bāda sūrat ḳhāna-e-ḳhamyāza thā',
          'shabnam ba-gul-e-lāla na ḳhālī z-adā hai \\ dāġh-e-dil-e-bedard nazar-gāh-e-hayā hai',
          'sham.a bujhtī hai to us meñ se dhuāñ uThtā hai \\ sho.ala-e-ishq siyah-posh huā mere ba.ad',
          'sham.a se hai bazm-e-añgusht-e-tahayyur dar dahan \\ sho.ala-e-āvāz-e-ḳhūbāñ par ba-hañgām-e-simā.a',
          'shaq ho gayā hai siina ḳhushā lazzat-e-farāġh \\ taklīf-e-parda-dāri-e-zaḳhm-e-jigar ga.ī',
          'shar.a o aa.iin par madār sahī \\ aise qātil kā kyā kare koī',
          'sharar hai rañg ba.ad iz.hār-e-tāb-e-jalva-e-tamkīñ \\ kare hai sañg par ḳhurshīd āb-e-rū-e-kār ātish',
          'sharm ik adā-e-nāz hai apne hī se sahī \\ haiñ kitne be-hijāb ki haiñ yuuñ hijāb meñ',
          'sharminda rakhte haiñ mujhe bād-e-bahār se \\ mīnā-e-be-sharāb o dil-e-be-havā-e-gul',
          'shauq hai sāmāñ-tarāz-e-nāzish-e-arbāb-e-ajz \\ zarra sahrā-dast-gāh o qatra dariyā-āshnā',
          'shauq har rañg raqīb-e-sar-o-sāmāñ niklā \\ qais tasvīr ke parde meñ bhī uryāñ niklā',
          'shauq us dasht meñ dauḌāye hai mujh ko ki jahāñ \\ jaada ġhair az nigah-e-dīda-e-tasvīr nahīñ',
          'shauq-e-dīdār meñ gar tū mujhe gardan maare \\ ho nigah misl-e-gul-e-shamā pareshāñ mujh se',
          'shikva-sañj-e-rashk-e-ham-dīgar na rahnā chāhiye \\ merā zaanū monis aur ā.īna terā āshnā',
          'shikve ke naam se be-mehr ḳhafā hotā hai \\ ye bhī mat kah ki jo kahiye to gila hotā hai',
          'shole se na hotī havas-e-shola ne jo kī \\ jī kis qadar afsurdagi-e-dil pe jalā hai',
          'shor hai kis bazm kī arz-e-jarāhat-ḳhāna kā \\ sub.h yak-bazm-e-namak sūd-e-charāġh-e-kushta hai',
          'shor-e-timsāl hai kis rashk-e-chaman kā yā rab \\ aa.ina baiza-e-bulbul nazar aatā hai mujhe',
          'shorish-e-bātin ke haiñ ahbāb munkir varna yaañ \\ dil muhīt-e-girya o lab āshnā-e-ḳhanda hai',
          "shoḳhi-e-iz.hār ġhair-az-vahshat-e-majnūñ nahīñ \\ lailā-e-manī 'asad' mahmil-nashīn-e-rāz hai",
          'shāyad ki mar gayā tire ruḳhsār dekh kar \\ paimāna raat maah kā labrez-e-nūr thā',
          'siine kā daaġh hai vo naala ki lab tak na gayā \\ ḳhaak kā rizq hai vo qatra ki dariyā na huā',
          'sitam-kash maslahat se huuñ ki ḳhūbāñ tujh pe āshiq haiñ \\ takalluf bartaraf mil jā.egā tujh sā raqīb āḳhir',
          'sohbat-e-rindāñ se vājib hai hazar \\ jā-e-mai apne ko khīñchā chāhiye',
          'surma-e-muft-e-nazar huuñ mirī qīmat ye hai \\ ki rahe chashm-e-ḳharīdār pe ehsāñ merā',
          'suḳhan meñ ḳhāma-e-ġhālib kī ātish-afshānī \\ yaqīñ hai ham ko bhī lekin ab us meñ dam kyā hai',
          'sābit huā hai gardan-e-mīnā pe ḳhūn-e-ḳhalq \\ larze hai mauj-e-mai tirī raftār dekh kar',
          'sādgī o purkārī be-ḳhudī o hushyārī \\ husn ko taġhāful meñ jur.at-āzmā paayā',
          'sādgī par us kī mar jaane kī hasrat dil meñ hai \\ bas nahīñ chaltā ki phir ḳhanjar kaf-e-qātil meñ hai',
          'sādgī-hā-e-tamannā ya.anī \\ phir vo nairañg-e-nazar yaad aayā',
          'sīkhe haiñ mah-ruḳhoñ ke liye ham musavvarī \\ taqrīb kuchh to bahr-e-mulāqāt chāhiye',
          'taaza nahīñ hai nashsha-e-fikr-e-suḳhan mujhe \\ tiryākī-e-qadīm huuñ dūd-e-charāġh kā',
          'tab.a hai mushtāq-e-lazzat-hā-e-hasrat kyā karūñ \\ aarzū se hai shikast-e-ārzū matlab mujhe',
          'tajāhul-peshgī se mudda.ā kyā \\ kahāñ tak ai sarāpā naaz kyā kyā',
          'takalluf sāz-e-rusvā.ī hai ġhāfil sharm-e-ranā.ī \\ dil-e-ḳhūñ-gashta dar dast-e-hinā-ālūda uryāñ hai',
          'takalluf-bar-taraf hai jāñ-sitāñ-tar lutf-e-bad-ḳhūyāñ \\ nigāh-e-be-hijāb-e-nāz teġh-e-tez-e-uryāñ hai',
          'takalluf-bartaraf farhād aur itnī subukdastī \\ ḳhayāl āsāñ thā lekin ḳhvāb-e-ḳhusrav ne girānī kī',
          'tamannā-e-zabāñ mahv-e-sipās-e-be-zabānī hai \\ miTā jis se taqāzā shikva-e-be-dast-o-pā.ī kā',
          'taufīq ba-andāza-e-himmat hai azal se \\ āñkhoñ meñ hai vo qatra ki gauhar na huā thā',
          'taġhāful bad-gumānī balki merī saḳht-jānī se \\ nigāh-e-be-hijāb-e-nāz ko bīm-e-gazand aayā',
          'taġhāful-mashrabī se nā-tamāmī bas-ki paidā hai \\ nigāh-e-nāz chashm-e-yār meñ zunnār-e-mīnā hai',
          'taḌap kar mar gayā vo said-e-bāl-afshāñ ki muztar thā \\ huā nāsū-e-chashm-e-ta.aziyat chashm-e-ḳhadañg āḳhir',
          'tere tausan ko sabā bāñdhte haiñ \\ ham bhī mazmūñ kī havā bāñdhte haiñ',
          'terī fursat ke muqābil ai umr \\ barq ko pa-ba-hinā bāñdhte haiñ',
          'terī vafā se kyā ho talāfī ki dahr meñ \\ tere sivā bhī ham pe bahut se sitam hue',
          'terī ārā.ish kā istiqbāl kartī hai bahār \\ jauhar-e-ā.īna hai yaañ naqsh-e-ehzār-e-chaman',
          'thak thak ke har maqām pe do chaar rah ga.e \\ terā pata na paa.eñ to nā-chār kyā kareñ',
          'thā zindagī meñ marg kā khaTkā lagā huā \\ uḌne se pesh-tar bhī mirā rañg zard thā',
          'thī nau-āmūz-e-fanā himmat-e-dushvār-pasand \\ saḳht mushkil hai ki ye kaam bhī āsāñ niklā',
          "thī vatan meñ shaan kyā 'ġhālib' ki ho ġhurbat meñ qadr \\ be-takalluf huuñ vo musht-e-ḳhas ki gulḳhan meñ nahīñ",
          'thī vo ik shaḳhs ke tasavvur se \\ ab vo rānā.ī-e-ḳhayāl kahāñ',
          'timsāl meñ terī hai vo shoḳhī ki ba-sad-zauq \\ ā.īna ba-andāz-e-gul āġhosh-kushā hai',
          'tire javāhīr-e-turf-e-kulah ko kyā dekheñ \\ ham auj-e-tāla-e-lāl-o-gohar ko dekhte haiñ',
          "tire va.ade par jiye ham to ye jaan jhuuT jaanā \\ ki ḳhushī se mar na jaate agar e'tibār hotā",
          'tire ḳhayāl se ruuh ehtizāz kartī hai \\ ba-jalva-rezi-e-bād-o-ba-par-fishānī-e-sham.a',
          'tirī nāzukī se jaanā ki bañdhā thā ahd bodā \\ kabhī tū na toḌ saktā agar ustuvār hotā',
          'tujh se qismat meñ mirī sūrat-e-qufl-e-abjad \\ thā likhā baat ke bante hī judā ho jaanā',
          'tum na aaoge to marne kī haiñ sau tadbīreñ \\ maut kuchh tum to nahīñ ho ki bulā bhī na sakūñ',
          'tum shahr meñ ho to hameñ kyā ġham jab uTheñge \\ le ā.eñge bāzār se jā kar dil o jaañ aur',
          "tum un ke va.ade kā zikr un se kyuuñ karo 'ġhālib' \\ ye kyā ki tum kaho aur vo kaheñ ki yaad nahīñ",
          'tumhārī tarz-o-ravish jānte haiñ ham kyā hai \\ raqīb par hai agar lutf to sitam kyā hai',
          'tumhīñ kaho ki guzārā sanam-parastoñ kā \\ butoñ kī ho agar aisī hī ḳhū to kyūñkar ho',
          'tā phir na intizār meñ niiñd aa.e umr bhar \\ aane kā ahd kar ga.e aa.e jo ḳhvāb meñ',
          'tā-kujā ai āgahī rañg-e-tamāshā bāḳhtan \\ chashm-e-vā-gardīda āġhosh-e-vidā-e-jalva hai',
          'tā-qayāmat shab-e-furqat meñ guzar jā.egī umr \\ saat din ham pe bhī bhārī haiñ sahar hote tak',
          'tālīf nusḳha-hā-e-vafā kar rahā thā maiñ \\ majmūa-e-ḳhayāl abhī fard fard thā',
          'tū aur ārā.ish-e-ḳham-e-kākul \\ maiñ aur andesha-hā-e-dūr-darāz',
          'tū dost kasū kā bhī sitamgar na huā thā \\ auroñ pe hai vo zulm ki mujh par na huā thā',
          'tū huā jalva-gar mubārak ho \\ rezish-e-sajda-e-jabīn-e-niyāz',
          'udhar vo bad-gumānī hai idhar ye nā-tavānī hai \\ na pūchhā jaa.e hai us se na bolā jaa.e hai mujh se',
          "ug rahā hai dar-o-dīvār se sabza 'ġhālib' \\ ham bayābāñ meñ haiñ aur ghar meñ bahār aa.ī hai",
          'ulajhte ho tum agar dekhte ho ā.īna \\ jo tum se shahr meñ hoñ ek do to kyūñkar ho',
          'ulfat-e-gul se ġhalat hai dāva-e-vārastagī \\ sarv hai bā-vasf-e-āzādī giraftār-e-chaman',
          'un ke dekhe se jo aa jaatī hai muñh par raunaq \\ vo samajhte haiñ ki bīmār kā haal achchhā hai',
          'unheñ manzūr apne zaḳhmiyoñ kā dekh aanā thā \\ uThe the sair-e-gul ko dekhnā shoḳhī bahāne kī',
          'us lab se mil hī jā.egā bosa kabhī to haañ \\ shauq-e-fuzūl o jur.at-e-rindāna chāhiye',
          'utnā hī mujh ko apnī haqīqat se bod hai \\ jitnā ki vahm-e-ġhair se huuñ pech-o-tāb meñ',
          'uzlat-guzīn-e-bazm haiñ vāmāñdagān-e-dīd \\ mīnā-e-mai hai aabla pā-e-nigāh kā',
          'uzr-e-vāmāndagī ai hasrat-e-dil \\ naala kartā thā jigar yaad aayā',
          'uḌtī phire hai ḳhaak mirī kū-e-yār meñ \\ baare ab ai havā havas-e-bāl-o-par ga.ī',
          'va.ada aane kā vafā kiije ye kyā andāz hai \\ tum ne kyuuñ sauñpī hai mere ghar kī darbānī mujhe',
          'vaa.e vaañ bhī shor-e-mahshar ne na dam lene diyā \\ le gayā thā gor meñ zauq-e-tan-āsānī mujhe',
          'vaañ kañgar-e-istiġhnā har-dam hai bulandī par \\ yaañ naale ko aur ulTā dāvā-e-rasā.ī hai',
          'vaañ vo ġhurūr-e-izz-o-nāz yaañ ye hijāb-e-pās-e-vaza.a \\ raah meñ ham mileñ kahāñ bazm meñ vo bulā.e kyuuñ',
          'vafā muqābil-o-dāvā-e-ishq be-buniyād \\ junūn-e-sāḳhta o fasl-e-gul qayāmat hai',
          'vafā-e-dilbarāñ hai ittifāqī varna ai hamdam \\ asar fariyād-e-dil-hā-e-hazīñ kā kis ne dekhā hai',
          'vahshat pe merī arsa-e-āfāq tañg thā \\ dariyā zamīn ko araq-e-infi.āl hai',
          'vahshat-e-ātish-e-dil se shab-e-tanhā.ī meñ \\ sūrat-e-dūd rahā saaya gurezāñ mujh se',
          'vahī ik baat hai jo yaañ nafas vaañ nik.hat-e-gul hai \\ chaman kā jalva baa.is hai mirī rañgīñ-navā.ī kā',
          'vahī sad-rañg nāla-farsā.ī \\ vahī sad-gona ashk-bārī hai',
          'vaqt hai gar bulbul-e-miskīñ zuleḳhā.i kare \\ yūsuf-e-gul jalva-farmā hai ba-bāzār-e-chaman',
          'vo aa.e ghar meñ hamāre ḳhudā kī qudrat hai \\ kabhī ham un ko kabhī apne ghar ko dekhte haiñ',
          'vo aayā bazm meñ dekho na kahiyo phir ki ġhāfil the \\ shakeb-o-sabr-e-ahl-e-anjuman kī āzmā.ish hai',
          'vo bad-ḳhū aur merī dāstān-e-ishq tūlānī \\ ibārat muḳhtasar qāsid bhī ghabrā jaa.e hai mujh se',
          'vo be-dimāġh-e-minnat-e-iqbāl huuñ ki maiñ \\ vahshat ba-dāġh-e-sāya-e-bāl-e-humā karūñ',
          'vo bhī din ho ki us sitamgar se \\ naaz khīñchūñ bajā.e hasrat-e-nāz',
          'vo bāda-e-shabāna kī sarmastiyāñ kahāñ \\ uThiye bas ab ki lazzat-e-ḳhvāb-e-sahar ga.ī',
          'vo dād-o-dīd garāñ-māya shart hai hamdam \\ vagarna mehr-e-sulaimān-o-jām-e-jam kyā hai',
          'vo firāq aur vo visāl kahāñ \\ vo shab-o-roz o māh-o-sāl kahāñ',
          "vo gul jis gulsitāñ meñ jalva-farmā.ī kare 'ġhālib' \\ chaTaknā ġhuncha-e-gul kā sadā-e-ḳhanda-e-dil hai",
          'vo halqa-hā-e-zulf kamīñ meñ haiñ yā ḳhudā \\ rakh liijo mere dāva-e-vārastagī kī sharm',
          'vo iltimās-e-lazzat-e-be-dād huuñ ki maiñ \\ teġh-e-sitam ko pusht-e-ḳham-e-iltijā karūñ',
          'vo naala dil meñ ḳhas ke barābar jagah na paa.e \\ jis naala se shigāf paḌe āftāb meñ',
          'vo neshtar sahī par dil meñ jab utar jaave \\ nigāh-e-nāz ko phir kyuuñ na āshnā kahiye',
          'vo sehr mudd.ā-talabī meñ na kaam aa.e \\ jis sehr se safīna ravāñ ho sarāb meñ',
          'vo zinda ham haiñ ki haiñ rū-shanās-e-ḳhalq ai ḳhizr \\ na tum ki chor bane umr-e-jāvedāñ ke liye',
          'vufūr-e-ashk ne kāshāne kā kiyā ye rañg \\ ki ho ga.e mire dīvār-o-dar dar-o-dīvār',
          "vus.at-e-mashrab niyāz-e-kulfat-e-vahshat 'asad' \\ yak-bayābāñ sāya-e-bāl-e-humā ho jā.iye",
          'vus.at-e-sa.i-e-karam dekh ki sar-tā-sar-e-ḳhāk \\ guzre hai ābla-pā abr-e-guhar-bār hunūz',
          'vā kar diye haiñ shauq ne band-e-naqāb-e-husn \\ ġhair-az-nigāh ab koī haa.il nahīñ rahā',
          'vā-e-dīvāngi-e-shauq ki har dam mujh ko \\ aap jaanā udhar aur aap hī hairāñ honā',
          'yaad hai shādī meñ bhī hañgāma-e-yā-rab mujhe \\ sub.ha-e-zāhid huā hai ḳhanda zer-e-lab mujhe',
          'yaañ talak merī giraftārī se vo ḳhush hai ki maiñ \\ zulf gar ban jā.ūñ to shāne meñ uljhā de mujhe',
          'yak qadam vahshat se dars-e-daftar-e-imkāñ khulā \\ jaada ajzā-e-do-ālam dasht kā shīrāza thā',
          'yak-qalam kāġhaz-e-ātish-zada hai safha-e-dasht \\ naqsh-e-pā meñ hai tab-e-garmī-e-raftār hunūz',
          'yak-zarra-e-zamīñ nahīñ be-kār baaġh kā \\ yaañ jaada bhī fatīla hai laale ke daaġh kā',
          "ye bā.is-e-naumīdi-e-arbāb-e-havas hai \\ 'ġhālib' ko burā kahte haiñ achchhā nahīñ karte",
          'ye ham jo hijr meñ dīvār-o-dar ko dekhte haiñ \\ kabhī sabā ko kabhī nāma-bar ko dekhte haiñ',
          "ye lāsh-e-be-kafan 'asad'-e-ḳhasta-jāñ kī hai \\ haq maġhfirat kare ajab āzād mard thā",
          'ye na thī hamārī qismat ki visāl-e-yār hotā \\ agar aur jiite rahte yahī intizār hotā',
          'ye parī-chehra log kaise haiñ \\ ġhamza o ishva o adā kyā hai',
          'ye rashk hai ki vo hotā hai ham-suḳhan tum se \\ vagarna ḳhauf-e-bad-āmozi-e-adū kyā hai',
          'ye zid ki aaj na aave aur aa.e bin na rahe \\ qazā se shikva hameñ kis qadar hai kyā kahiye',
          'yuuñ hī dukh kisī ko denā nahīñ ḳhuub varna kahtā \\ ki mire adū ko yā rab mile merī zindagānī',
          'yā rab is āshuftagī kī daad kis se chāhiye \\ rashk āsā.ish pe hai zindāniyoñ kī ab mujhe',
          'yā-rab vo na samjhe haiñ na samjheñge mirī baat \\ de aur dil un ko jo na de mujh ko zabāñ aur',
          'yā-rab zamāna mujh ko miTātā hai kis liye \\ lauh-e-jahāñ pe harf-e-mukarrar nahīñ huuñ maiñ',
          'za-bas-ki mashq-e-tamāshā junūñ-alāmat hai \\ kushād-o-bast-e-mizhah sīli-e-nadāmat hai',
          'zabān-e-ahl-e-zabāñ meñ hai marg-e-ḳhāmoshī \\ ye baat bazm meñ raushan huī zabānī-e-sham.a',
          'zahe karishma ki yuuñ de rakkhā hai ham ko fareb \\ ki bin kahe hī unheñ sab ḳhabar hai kyā kahiye',
          'zahr miltā hī nahīñ mujh ko sitamgar varna \\ kyā qasam hai tire milne kī ki khā bhī na sakūñ',
          'zakāt-e-husn de ai jalva-e-bīnish ki mehr-āsā \\ charāġh-e-ḳhāna-e-darvesh ho kaasa gadā.ī kā',
          'zarra zarra sāġhar-e-mai-ḳhāna-e-nai-rañg hai \\ gardish-e-majnūñ ba-chashmak-hā-e-lailā āshnā',
          'zaḳhm ne daad na dī tañgi-e-dil kī yā rab \\ tiir bhī sīna-e-bismil se par-afshāñ niklā',
          'zaḳhm silvāne se mujh par chārā-juī kā hai taan \\ ġhair samjhā hai ki lazzat zaḳhm-e-sozan meñ nahīñ',
          'zaḳhmī huā hai pāshna pā-e-sabāt kā \\ ne bhāgne kī guuñ na iqāmat kī taab hai',
          'zikr us parī-vash kā aur phir bayāñ apnā \\ ban gayā raqīb āḳhir thā jo rāz-dāñ apnā',
          "zindagī apnī jab is shakl se guzrī 'ġhālib' \\ ham bhī kyā yaad kareñge ki ḳhudā rakhte the",
          'zindagī meñ to vo mahfil se uThā dete the \\ dekhūñ ab mar ga.e par kaun uThātā hai mujhe',
          'zo.af meñ tāna-e-aġhyār kā shikva kyā hai \\ baat kuchh sar to nahīñ hai ki uThā bhī na sakūñ',
          'zo.af se girya mubaddal ba-dam-e-sard huā \\ bāvar aayā hameñ paanī kā havā ho jaanā',
          'zof se ai girya kuchh baaqī mire tan meñ nahīñ \\ rañg ho kar uḌ gayā jo ḳhuuñ ki dāman meñ nahīñ',
          'zof-e-junūñ ko vaqt-e-tapish dar bhī duur thā \\ ik ghar meñ muḳhtasar sā bayābāñ zarūr thā',
          'zālim mire gumāñ se mujhe munfa.il na chaah \\ hai hai ḳhudā-na-karda tujhe bevafā kahūñ',
          'ā.īna dekh apnā sā muñh le ke rah ga.e \\ sāhab ko dil na dene pe kitnā ġhurūr thā',
          'ā.īna kyuuñ na duuñ ki tamāshā kaheñ jise \\ aisā kahāñ se lā.ūñ ki tujh sā kaheñ jise',
          'āshiq hue haiñ aap bhī ek aur shaḳhs par \\ āḳhir sitam kī kuchh to mukāfāt chāhiye',
          'āshiq naqāb-e-jalva-e-jānāna chāhiye \\ fānūs-e-sham.a ko par-e-parvāna chāhiye',
          'āshiqī sabr-talab aur tamannā betāb \\ dil kā kyā rañg karūñ ḳhūn-e-jigar hote tak',
          "āshnā 'ġhālib' nahīñ haiñ dard-e-dil ke āshnā \\ varna kis ko mere afsāne kī tāb-e-istimā.a",
          'ātish-parast kahte haiñ ahl-e-jahāñ mujhe \\ sargarm-e-nāla-hā-e-sharar-bār dekh kar',
          'āzādī-e-nasīm mubārak ki har taraf \\ TuuTe paḌe haiñ halqa-e-dām-e-havā-e-gul',
          'ġhaflat-matā-e-kaffa-e-mīzān-e-adl huuñ \\ yā rab hisāb-e-saḳhti-e-ḳhvāb-e-girāñ na pūchh',
          'ġhair leñ mahfil meñ bose jaam ke \\ ham raheñ yuuñ tishna-lab paiġhām ke',
          'ġhalatī-hā-e-mazāmīñ mat pūchh \\ log naale ko rasā bāñdhte haiñ',
          'ġham us ko hasrat-e-parvāna kā hai ai sho.ale \\ tire larazne se zāhir hai nā-tavānī-e-sham.a',
          'ġham āġhosh-e-balā meñ parvarish detā hai āshiq ko \\ charāġh-e-raushan apnā qulzum-e-sarsar kā marjāñ hai',
          'ġham-e-duniyā se gar paa.ī bhī fursat sar uThāne kī \\ falak kā dekhnā taqrīb tere yaad aane kī',
          'ġham-e-ushshāq na ho sādgī-āmoz-e-butāñ \\ kis qadar ḳhāna-e-ā.īna hai vīrāñ mujh se',
          'ġhuncha tā shaguftan-hā barg-e-āfiyat mālūm \\ bā-vajūd-e-dil-jam.ī ḳhvāb-e-gul pareshāñ hai',
          'ġhāfil ba-vahm-e-nāz ḳhud-ārā hai varna yaañ \\ be-shāna-e-sabā nahīñ turra gayāh kā',
          'ġhāfil in mah-tal.atoñ ke vāste \\ chāhne vaalā bhī achchhā chāhiye',
          "ġhālib' apnā ye aqīda hai ba-qaul-e-'nāsiḳh' \\ aap be-bahra hai jo mo'taqid-e-'mīr' nahīñ",
          'ījād kartī hai use tere liye bahār \\ merā raqīb hai nafas-e-itr-sā-e-gul',
          'ḳhaar ḳhār-e-alam-e-hasrat-e-dīdār to hai \\ shauq gul-chīn-e-gulistān-e-tasallī na sahī',
          'ḳhalish-e-ġhamza-e-ḳhūñ-rez na pūchh \\ dekh ḳhūnāba-fishānī merī',
          'ḳhalvat-e-ābila-e-pā meñ hai jaulāñ merā \\ ḳhuuñ hai dil tañgī-e-vahshat se bayābāñ merā',
          'ḳhamoshiyoñ meñ tamāshā adā nikaltī hai \\ nigāh dil se tire surma-sā nikaltī hai',
          'ḳhastagī kā tum se kyā shikva ki ye \\ hathkanDe haiñ charḳh-e-nīlī-fām ke',
          'ḳhat likheñge garche matlab kuchh na ho \\ ham to āshiq haiñ tumhāre naam ke',
          'ḳhat-e-nau-ḳhez nīl-e-chashm zaḳhm-e-sāfī-e-āriz \\ liyā ā.īna ne hirz-e-par-e-tūtī ba-chang āḳhir',
          'ḳhatar hai rishta-e-ulfat rag-e-gardan na ho jaave \\ ġhurūr-e-dostī aafat hai tū dushman na ho jaave',
          'ḳhatt-e-āriz se likhā hai zulf ko ulfat ne ahd \\ yak-qalam manzūr hai jo kuchh pareshānī kare',
          'ḳhayāl-e-dūd thā sar-josh-e-saudā-e-ġhalat-fahmī \\ agar rakhtī na ḳhākistar-nashīnī kā ġhubār ātish',
          'ḳhayāl-e-marg kab taskīñ dil-e-āzurda ko baḳhshe \\ mire dām-e-tamannā meñ hai ik said-e-zabūñ vo bhī',
          'ḳhizāñ kyā fasl-e-gul kahte haiñ kis ko koī mausam ho \\ vahī ham haiñ qafas hai aur mātam bāl-o-par kā hai',
          'ḳhud-faroshī-hā-e-hastī bas-ki jā-e-ḳhanda hai \\ har shikast-e-qīmat-e-dil meñ sadā-e-ḳhanda hai',
          'ḳhud-parastī se rahe bāham-digar nā-āshnā \\ bekasī merī sharīk ā.īna terā āshnā',
          'ḳhudāyā jazba-e-dil kī magar tāsīr ulTī hai \\ ki jitnā khīñchtā huuñ aur khiñchtā jaa.e hai mujh se',
          'ḳhush uftādgī ki ba-sahrā-e-intizār \\ juuñ jaada gard-e-rah se nigah surma-sā karūñ',
          'ḳhush vahshate ki arz-e-junūn-e-fanā karūñ \\ juuñ gard-e-rāh jāma-e-hastī qabā karūñ',
          'ḳhush-hāl us harīf-e-siyah-mast kā ki jo \\ rakhtā ho misl-e-sāya-e-gul sar-ba-pā-e-gul',
          'ḳhuuñ hai dil ḳhaak meñ ahvāl-e-butāñ par ya.anī \\ un ke nāḳhun hue mohatāj-e-hinā mere ba.ad',
          'ḳhāna hai sail se ḳhū-karda-e-dīdār hunūz \\ dūrbīñ dar-zada hai raḳhna-e-dīvār hunūz',
          'ḳhū ne tirī afsurda kiyā vahshat-e-dil ko \\ māshūqī o be-hauslagī tarfa balā hai']


def send_tweet():
    num_of_verses = len(lyrics)
    len_for_randint = num_of_verses - 1
    tweet_prefix = " "
    random_verse = lyrics[randint(0, len_for_randint)]
    actual_tweet = tweet_prefix + random_verse
    client.create_tweet(text=actual_tweet)


# defining the main function by combining the two main functions

def main_code():
    send_tweet()
    time.sleep(60 * 60 * 4)
    # for i in range(480):
    # reply()
    # time.sleep(30)


while True:
    try:
        main_code()
    except Exception as e:
        # sometimes twitter is over capacity so sleep then continue
        time.sleep(30)
        continue
